---
author: "yincy"
date: "1/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r, message=FALSE, warning=FALSE}
library(magrittr)
library(data.table)
library(org.Mm.eg.db)
library(scater)
library(scran)
```

```{r}
GSE107585 <- fread("/home/yincy/git/Data/kidney-single-cell/GSE107585/GSE107585_Mouse_kidney_single_cell_datamatrix.txt.gz", 
                   sep = "\t")
GSE107585 %>% dim()
GSE107585[1:4, 1:4]


cdata <- data.frame(
  cellid = colnames(GSE107585) %>% .[-1], 
  cluster = GSE107585[1, , drop = T] %>% as.character() %>% .[-1] %>% as.integer()
)

celltype = c("1" = "Endo", 
             "2" = "Podo", 
             "3" = "PT", 
             "4" = "LOH", 
             "5" = "DCT", 
             "6" = "CD-PC", 
             "7" = "CD-IC", 
             "8" = "CD-Trans", 
             "9" = "Novel1", 
             "10" = "Fib", 
             "11" = "Macro", 
             "12" = "Neutro", 
             "13" = "B lymph", 
             "14" = "T lymph", 
             "15" = "NK", 
             "16" = "Novel2")
cdata$celltype = celltype[cdata$cluster]


GSE107585 <- GSE107585[-1, ]
GSE107585 <- GSE107585 %>% rename("V1" = "symbol") 

rdata <- data.frame(
  symbol = GSE107585$symbol
)

rdata$ensembl <- mapIds(org.Mm.eg.db, 
                        keys = rdata$symbol, 
                        keytype = "SYMBOL", 
                        column = "ENSEMBL")

GSE107585 <- GSE107585 %>% tibble::column_to_rownames("symbol")

sce.kidney <- SingleCellExperiment(assays = list(counts = GSE107585 %>% as.matrix()), 
                                   rowData = rdata, 
                                   colData = cdata)

sce.kidney <- computeSumFactors(sce.kidney, clusters = sce.kidney$cluster)
sce.kidney <- logNormCounts(x = sce.kidney)

sce.kidney <- readRDS("/home/yincy/git/Data/kidney-single-cell/GSE107585/sce.kidney_GSE107585.rds")

mexper <- tapply(assay(sce.kidney[rownames(sce.kidney) == "Cx3cl1", ], "logcounts"), sce.kidney$celltype, mean, na.rm = T) %>% 
  sort(decreasing = T)

sce.kidney$celltype <- factor(sce.kidney$celltype, levels = names(mexper))

plotExpression(sce.kidney, 
               features = c("Cx3cr1", "Cx3cl1"), 
               x = "celltype", 
               colour_by = "celltype", 
               ncol = 1) +
    scale_fill_discrete(name = NULL, type = c(brewer.pal(9, "Set1"), brewer.pal(7, "Dark2"))) +
    scale_x_discrete(name = NULL) +
    scale_y_continuous(name = "expression") +
    theme(axis.text.x = element_text(angle = -40, hjust = 0), 
          legend.position = "none") 

ggsave("/home/yincy/git/Data/kidney-single-cell/GSE107585/Cx3cr1-Cx3cl1-expression.tiff", 
       width = 10, height = 6)
```



