---
title: "r4ds"
author: "yincy"
date: "3/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## string  
```{r}
library(stringr)
```

```{r}
str_c("x", "y", sep = ", ")
```

```{r}
str_c("prefic-", c("a", "b", "c"), "-suffix")
```

```{r}
str_c(c("x", "y", "z"), collapse = ", ")
```

```{r}
x <- c("andi", "djwo", "1")
str_length(x)
nchar(x)
```

```{r}
x <- "a\\b"
writeLines(x)

str_view(x, "\\\\")
```

```{r}
str_split(c("abcdefgh"), pattern = "", simplify = F) 
```


## Factors  
```{r}
x1 <- c("Dec", "Apr", "Jan", "Mar")
x2 <- c("Dec", "Apr", "Jam", "Mar")
```


```{r}
sort(x1)
```

```{r}
month_levels <- c(
  "Jan", "Feb", "Mar", "Apr", "May", "Jun", 
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
)
```


```{r}
y1 <- factor(x1, levels = month_levels)
```

```{r}
sort(y1)
```


```{r}
gss_cat %>% 
  count(race)
```

```{r}
gss_cat %>% 
  ggplot(aes(race)) +
  geom_bar()
```

```{r}
ggplot(gss_cat, aes(race)) +
  geom_bar() +
  scale_x_discrete(drop = F)
```


```{r}
relig_summary <- gss_cat %>% 
  group_by(relig) %>% 
  summarise(
    age = mean(age, na.rm = T), 
    tvhours =  mean(tvhours, na.rm = T), 
    n = n()
  )

relig_summary %>% 
  ggplot(aes(tvhours, relig)) +
  geom_point()
```

```{r}
relig_summary %>% 
  ggplot(aes(tvhours, fct_reorder(relig, tvhours))) +
  geom_point()
```

```{r}
relig_summary %>% 
  mutate(relig = fct_reorder(relig, tvhours)) %>% 
  ggplot(aes(tvhours, relig)) +
  geom_point()
```



```{r}
rincome_summaty <- gss_cat %>% 
  group_by(rincome) %>% 
  summarise(
    age = mean(age, na.rm = T), 
    tvhours = mean(tvhours, na.rm = T), 
    n = n()
  )
```


```{r}
rincome_summaty %>% 
  ggplot(aes(age, fct_relevel(rincome, "Not applicable"))) +
  geom_point()
```

```{r}
gss_cat
```


```{r}
gss_cat %>% 
  mutate(partyid = fct_recode(partyid, 
                              "Republican, strong"   = "Strong republican", 
                              "Republican, weak"     = "Not str republican", 
                              "Independent, near rep"= "Ind,near rep", 
                              "Independent, near dem"= "Ind,near dem", 
                              "Democrat, weak"       = "Not str democrat", 
                              "Democrat, strong"     = "Strong democrat")) %>% 
  count(partyid)
```

```{r}
gss_cat %>% 
  mutate(partyid = fct_collapse(partyid, 
                                other = c("No answer", "Don't know", "Other party"), 
                                rep = c("Strong republican", "Not str republican"), 
                                ind = c("Ind,near rep", "Independent", "Ind,near dem"), 
                                dem = c("Not str democrat", "Strong democrat"))) %>% 
  count(partyid)
```

```{r}
gss_cat %>% 
  mutate(relig = fct_lump(relig)) %>% 
  count(relig)
```

```{r}
gss_cat %>% 
  mutate(relig = fct_lump(relig, prop = 0.01)) %>% 
  count(relig)
```

```{r}
gss_cat %>% 
  mutate(relig = fct_lump(relig, n = 6)) %>% 
  count(relig)
```


## model  
```{r}
library(tidyverse)
library(modelr)
```

```{r}
models <- tibble(
  a1 = runif(250, -20, 40), 
  a2 = runif(250, -5, 5)
)

ggplot(sim1, aes(x, y)) +
  geom_point()
```

```{r}
ggplot(sim1, aes(x, y)) +
  geom_point() +
  geom_abline(data = models, aes(intercept = a1, slope =a2), alpha = 1/4)
```

```{r}
model1 <- function(a, data){
  a[1] + data$x * a[2]
}

model1(c(7, 1.5), sim1)
```


```{r}
measure_distance <- function(mod, data){
  diff = data$y - model1(mod, data)
  sqrt(mean(diff^2))
}

measure_distance(c(7, 1.5), sim1)
```

```{r}
sim1_dist <- function(a1, a2){
  measure_distance(c(a1, a2), sim1)
}

models <- models %>% 
  mutate(dist = purrr::map2_dbl(a1, a2, sim1_dist))

models
```


```{r}
ggplot(sim1, aes(x, y)) +
  geom_point() +
  geom_abline(aes(intercept = a1, slope = a2, color = -dist), 
              data = models %>% filter(rank(dist) <= 10))
```


```{r}
ggplot(models, aes(a1, a2)) +
  geom_point(aes(a1, a2), data = models %>% filter(rank(dist) <= 10), size = 4, color = "red") +
  geom_point()
```


