---
title: "regular expression"
author: "yincy"
date: "4/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


```{r}
homicides <- readLines(con = "homicides.txt")
homicides[1]
homicides[1000]
```

```{r}
grep("iconHomicideShooting", homicides) %>% length()
grep("iconHomicideShooting|icon_homicide_shooting", homicides) %>% length()
grep("Cause: shooting", homicides) %>% length()
grep("Cause: [Ss]hooting", homicides) %>% length()
grep("[Ss]hooting", homicides) %>% length()
```

```{r}
i <- grep("[Cc]ause: [Ss]hooting", homicides)
j <- grep("[Ss]hooting", homicides)
str(i)
str(j)
setdiff(j, i)
```

```{r}
x <- regexpr(pattern = "<dd>[F\f]ound(.*?)</dd>", text = homicides[1:10])
```

```{r}
y <- substr(homicides[1:10], start = x, stop = (x + attr(x, "match.length")) - 1)
```


```{r}
d <- gsub("<dd>[F|f]ound on |</dd>", "", y)
as.Date(d, format = "%B %d, %Y")
```


```{r}
x <- regexec("<dd>[F|f]ound on (.*?)</dd>", homicides[1])
```

```{r}
substr(homicides[1], start = x[[1]][2], stop = (x[[1]][2] + attr(x[[1]], "match.length")[2]) - 1)
```

```{r}
r <- regexec(pattern = "<dd>[F|f]ound on (.*?)</dd>", homicides)
m <- regmatches(homicides, r)
date <- sapply(m, function(x) x[2])
dates <- as.Date(date, "%B %d, %Y")
hist(dates, "month", freq = T)
```

```{r}
sapply(regmatches(homicides, r), function(x)x[2]) %>% as.Date(format = "%B %d, %Y") %>% hist("month")
```




































