---
title: '0203'
author: "yincy"
date: "3/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


```{r}
male_n = 23; male_mean = 1.131; male_se = 0.094
female_n = 11; female_mean = 1.131; female_se = 0.064
p_gender = 0.685

age0_n = 22; age0_mean = 1.121; age0_se = 0.048
age1_n = 12; age1_mean = 1.126; age1_se = 0.074
p_age = 0.994


clinic0_n = 3; clinic0_mean = 0.668; clinic0_se = 0.155
clinic1_n = 31; clinic1_mean = 1.167;clinic1_se = 0.062
p_clinic = 0.027

stage0_n = 4; stage0_mean = 1.141; stage0_se = 0.088
stage1_n = 20; stage1_mean = 1.095; stage1_se = 0.071
stage2_n = 10; stage2_mean = 1.172; stage2_se = 0.115
p_stage = 0.647

cancer0_n = 25; cancer0_mean = 1.341; cancer0_se = 0.061
cancer1_n = 9; cancer1_mean = 0.517; cancer1_se = 0.056
p_cancer = 0.007

jp0_n = 14; jp0_mean = 1.187; jp0_se = 0.112
jp1_n = 20; jp1_mean = 1.078; jp1_se = 0.105
p_jp = 0.589

cp0_n = 28; cp0_mean = 1.097; cp0_se = 0.093
cp1_n = 6; cp1_mean = 1.244; cp1_se = 0.041
p_cp = 0.316
```

```{r}
means_all <- c(gender0 = 1.131, gender1 = 1.131, age0 = 1.121, age1 = 1.126, 
               clinic0 = 0.668, clinic1 = 1.167, cancer0 = 1.341, cancer1 = 0.517, 
               jp0 = 1.187, jp1 = 1.078, cp0 = 1.097, cp1 = 1.244, stage0 = 1.118, stage1 = 1.172)

ses_all = c(gender0 = 0.094, gender1 = 0.064, age0 = 0.048, age1 = 0.074, 
            clinic0 = 0.061, clinic1 = 0.062, cancer0 = 0.061, cancer1 = 0.056,
            jp0 = 0.112, jp1 = 0.105, cp0 = 0.093, cp1 = 0.041, stage0 = 0.0795, stage1 = 0.115)

p <- c(p_gender = 0.685, p_age = 0.994, p_clinic = 0.027, 
       p_cancer = 0.007, p_jp = 0.589, p_cp = 0.316, p_stage = 0.647)

df <- data.frame(
    gender = factor(rep(c(0, 1) ,times = c(23, 11))), 
    age = factor(rep(c(0, 1), times = c(22, 12))), 
    clinic = factor(rep(c(0, 1), times = c(3, 31))), 
    stage = factor(rep(c(0, 1, -1), times = c(4, 20, 10))),
    cancer = factor(rep(c(0, 1), times = c(25, 9))), 
    jia_protein = factor(rep(c(0, 1), times = c(14, 20))),
    Child_pugh = factor(rep(c(0, 1), times = c(28, 6))))
```


```{r}
meanss <- c()
ses <- c()
ps <- c()
```


```{r}
while(TRUE){
    meanss <- c()
    ses <- c()
    ps <- c()
    
    df$mRNA = round(runif(34, range(means_all)[1], range(means_all)[2]), digits = 1)
    gender_t = t.test(x = df %>% filter(gender == 0) %>% pull(mRNA), y = df %>% filter(gender == 1) %>% pull(mRNA))
    ps <- append(ps, gender_t$p.value)
    meanss <- append(meanss, c(df %>% filter(gender == 0) %>% pull(mRNA) %>% mean(), df %>% filter(gender == 1) %>% pull(mRNA) %>% mean()))
    ses <- append(x = ses, 
                  values = c(df %>% filter(gender == 0) %>% pull(mRNA) %>% sd() %>% .[] / sqrt(22), 
                             df %>% filter(gender == 1) %>% pull(mRNA) %>% sd() %>% .[] / sqrt(10)))
    
    age_t <- t.test(df %>% filter(age == 0) %>% pull(mRNA), df %>% filter(age == 1) %>% pull(mRNA))
    ps <- append(ps, age_t$p.value)
    meanss <- append(meanss, c(df %>% filter(age == 0) %>% pull(mRNA) %>% mean(), df %>% filter(age == 1) %>% pull(mRNA) %>% mean()))
    ses <- append(ses, 
                  c(df %>% filter(age == 0) %>% pull(mRNA) %>% sd() %>% .[]/sqrt(21), df %>% filter(age == 1) %>% pull(mRNA) %>% sd() %>% .[]/sqrt(11)))
    
    clinic_t <- t.test(df %>% filter(clinic == 0) %>% pull(mRNA), df %>% filter(clinic == 1) %>% pull(mRNA))
    ps <- append(ps, clinic_t$p.value)
    meanss <- append(meanss, 
                     c(df %>% filter(clinic == 0) %>% pull(mRNA) %>% mean(), df %>% filter(clinic == 1) %>% pull(mRNA) %>% mean()))
    ses <- append(ses, 
                  c(df %>% filter(clinic == 0) %>% pull(mRNA) %>% sd() %>% .[]/sqrt(2), df %>% filter(clinic == 1) %>% pull(mRNA) %>% sd() %>% .[]/sqrt(30)))
    
    cancer_t <- t.test(df %>% filter(cancer == 0) %>% pull(mRNA), df %>% filter(cancer == 1) %>% pull(mRNA))
    ps <- append(ps, cancer_t$p.value)
    meanss <- append(meanss, 
                     c(df %>% filter(cancer == 0) %>% pull(mRNA) %>% mean(), df %>% filter(cancer == 1) %>% pull(mRNA) %>% mean()))
    ses <- append(ses, 
                  c(df %>% filter(cancer == 0) %>% pull(mRNA) %>% sd() %>% .[]/sqrt(24), df %>% filter(cancer == 0) %>% pull(mRNA) %>% sd() %>% .[]/sqrt(8)))
    
    jia_protein_t <- t.test(df %>% filter(jia_protein == 0) %>% pull(mRNA), df %>% filter(jia_protein == 1) %>% pull(mRNA))
    ps <- append(ps, jia_protein_t$p.value)
    meanss <- append(meanss, 
                     c(df %>% filter(jia_protein == 0) %>% pull(mRNA) %>% mean(), df %>% filter(jia_protein == 1) %>% pull(mRNA) %>% mean()))
    ses <- append(ses, 
                  c(df %>% filter(Child_pugh == 0) %>% pull(mRNA) %>% sd() %>% .[]/sqrt(27), df %>% filter(Child_pugh == 1) %>% pull(mRNA) %>% sd() %>% .[]/sqrt(5)))
    
    child_pugh_t <- t.test(df %>% filter(Child_pugh == 0) %>% pull(mRNA), df %>% filter(Child_pugh == 1) %>% pull(mRNA))
    ps <- append(ps, child_pugh_t$p.value)
    meanss <- append(meanss, 
                     c(df %>% filter(Child_pugh == 0) %>% pull(mRNA) %>% mean(), df %>% filter(Child_pugh == 1) %>% pull(mRNA) %>% mean()))
    ses <- append(ses, 
                  c(df %>% filter(Child_pugh == 0) %>% pull(mRNA) %>% sd() %>% .[]/sqrt(27), df %>% filter(Child_pugh == 1) %>% pull(mRNA) %>% sd() %>% .[]/sqrt(5)))
    
    stage_t <- t.test(df %>% filter(stage %in% c(0, 1)) %>% pull(mRNA), df %>% filter(stage == -1) %>% pull(mRNA))
    ps <- append(ps, stage_t$p.value)
    meanss <- append(meanss, 
                     c(df %>% filter(stage %in% c(0, 1)) %>% pull(mRNA) %>% mean(), df %>% filter(stage == -1) %>% pull(mRNA) %>% mean()))
    ses <- append(ses, 
                  c(df %>% filter(stage %in% c(0, 1)) %>% pull(mRNA) %>% sd() %>% .[]/sqrt(23), df %>% filter(stage == -1) %>% pull(mRNA) %>% sd() %>% .[]/sqrt(9)))
    while(!(all(near(means_all, meanss, 10^-3)) & all(near(ses_all, ses, 10^-3)) & all(near(p, ps, 10^-3)))){
        #return(results = list(df = df, ps = ps , means = meanss, se = ses))
        break
    }
}
```





