---
title: "P2y12r and C1q"
author: "yincy"
date: "9/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
library(nichenetr)
library(EnsDb.Mmusculus.v79)
library(KEGGREST)
library(pathview)
library(KEGGgraph)
library(biomaRt)
library(igraph)
```


# C1q and C3 regulators   
```{r}
mgs <- genes(EnsDb.Mmusculus.v79)

C1q <- mgs[grep("^C1q", mgs$gene_name, ignore.case = T)]$gene_name %>% unique()
C1q

write.csv(x = c(C1q, "C3") %>% sort(), 
            file = "C1 and C3 genes.csv", 
          row.names = F, quote = F)
```

```{r}
load(file = "f:/git/nichenetr/data/gr_network.rda")

# convert from human to muse symbol
gr_network$from <- gr_network$from %>% convert_human_to_mouse_symbols()
gr_network$to <- gr_network$to %>% convert_human_to_mouse_symbols()

gr_network <- gr_network %>% 
    dplyr::filter(!is.na(from), !is.na(to))

gr_network %>% 
    dplyr::filter(toupper(to) %in% toupper(c(C1q, "C3"))) %>% 
    dplyr::select(from, to) %>% 
    arrange(to) %>% 
    magrittr::set_colnames(value = c("regulator", "target")) %>% 
    write.csv(file = "C1C3-regulators.csv", 
                row.names = F, quote = F)
```


Download KEGG pathways  
```{r}
mmu_pathways <- keggList(database = "pathway", organism = "mmu")
mmu_pathways <- mmu_pathways %>% 
    names() %>% 
    gsub(pattern = "path:mmu", replacement = "", x = .)

download.kegg(pathway.id = mmu_pathways, 
              species = "mmu", 
              kegg.dir = "/home/yincy/git/Data/KEGG/pathways/mouse/", 
              file.type = "xml")
```


# P2y12r signaling network  
## PVN  
```{r}
pvn <- read.csv(file = "20200702_frame_tpm_coding_gene_PVN.csv", 
                row.names = 1)
pvn
```

samples  
```{r}
A14 <- grep("14A", colnames(pvn), value = T)
L14 <- grep("14L", colnames(pvn), value = T)
A3 <- grep("3A", colnames(pvn), value = T)
L3 <- grep("3L", colnames(pvn), value = T)
naive <- grep("naive", colnames(pvn), value = T)
```

fold changes  
```{r}
FC_df <- pvn %>% 
    rownames_to_column(var = "ensembl") %>% 
    rowwise() %>% 
    mutate(
        mean_A14 = mean(PVN_14A1, PVN_14A2, PVN_14A3), 
        mean_L14 = mean(PVN_14L1, PVN_14L2_b1, PVN_14L3_b1, PVN_14L4, PVN_14L5, PVN_14L6), 
        mean_A3 = mean(PVN_3A1_b1, PVN_3A2, PVN_3A3_b1), 
        mean_L3 = mean(PVN_3L1_b1, PVN_3L2_b1, PVN_3L3), 
        mean_naive = mean(PVN_naive1, PVN_naive2, PVN_naive3), 
        FC_A14 = mean_A14 / mean_naive, 
        FC_L14 = mean_L14 / mean_naive, 
        FC_A3 = mean_A3 / mean_naive, 
        FC_L3 = mean_L3 / mean_naive) %>% 
    relocate(geneid_symbol, ensembl, starts_with("FC_"), starts_with("mean")) 

FC_df[!duplicated(FC_df$geneid_symbol), ]
```

```{r}
agg_FC_df <- aggregate.data.frame(FC_df[, 3:6], list(FC_df$geneid_symbol), FUN = "sum") %>% 
    column_to_rownames("Group.1")
agg_FC_df
```

```{r}
agg_FC_df_log2 <- agg_FC_df %>% log2()

for(i in dim(agg_FC_df_log2)[1]){
    for(j in dim(agg_FC_df_log2)[2]){
        ifelse(agg_FC_df_log2[i, j] == -Inf, -5, agg_FC_df_log2[i, j])
        ifelse(agg_FC_df_log2[i, j] == Inf, 5, agg_FC_df_log2[i, j])
        ifelse(is.na(agg_FC_df_log2[i, j]), 0, agg_FC_df_log2[i, j])
        ifelse(abs(agg_FC_df_log2[i, j]) > 5, 5 * sign(agg_FC_df_log2[i, j]), agg_FC_df_log2[i, j])
    }
}

agg_FC_df_log2
```

```{r}
par(mfrow = c(3, 1))
plot(agg_FC_df_log2$FC_A14, agg_FC_df$FC_L14, pch = 19, xlim = c(-9, 9), ylim = c(-9, 9))
hist(agg_FC_df_log2$FC_A14, breaks = 30)
hist(agg_FC_df_log2$FC_L14, breaks = 30)
```


## map p2y12r onto KEGG pathways  
```{r}
p2ry12_entrez <- "70839"
mgs[grep("p2ry12", mgs$gene_name, ignore.case = T, value = F)]
```

```{r}
keggLink(target = "pathway", source = paste("mmu:", p2ry12_entrez, sep = ""))
```

```{r}
pathview(gene.data = agg_FC_df, 
         pathway.id = "04611", 
         kegg.native = F, 
         species = "mmu", 
         gene.idtype = "SYMBOL", 
         cpd.lab.offset = 0, 
         cex = 0.4, 
         min.nnodes = 1, 
         trans.fun = list(gene = log2), 
         multi.state =F, 
         limit = list(gene = c(-5, 5), cpd = c(-5, 5)))
```


## parse pathway to data frame   
```{r}
KGML_files <- list.files(path = "f:/mmu_kegg_xml/", full.names = T, pattern = ".xml$")
# KGML_files <- KGML_files[file.size(KGML_files) < 2300000]

df <- data.frame()
for(i in KGML_files){
    pathway <- do.call(
        what = "parseKGML2DataFrame", 
        args = list(
            file = i, 
            genesOnly = T, 
            expandGene = T
        )
    )
    df <- rbind(df, pathway)
}

df <- df %>% as_tibble()
write.csv(x = df, file = "all_path_dataframe.csv", 
          row.names = F, 
          quote = F)

all_path_df <- read.csv(file = "all_path_dataframe.csv", 
                        stringsAsFactors = F)
all_path_df %>% dim()
all_path_df %>% pull(type) %>% table()
all_path_df %>% pull(subtype) %>% table()

all_path_df %>% head()
all_path_df <- all_path_df %>% distinct(from, to, .keep_all = T)

from <- all_path_df %>% pull(from)
to <- all_path_df %>% pull(to)
c(from, to) %>% unique() %>% length()
```

```{r}
all_path_df$from <- gsub("mmu:", "", all_path_df$from)
all_path_df$to <- gsub("mmu:", "", all_path_df$to)
all_path_df
```

```{r}
mmart <- useMart(biomart = "ensembl", dataset = "mmusculus_gene_ensembl")
from_df <- getBM(attributes = c("entrezgene_id", "mgi_symbol"), 
                 filters = "entrezgene_id", 
                 values = all_path_df[, "from"] %>% unique(), 
                 mart = mmart)
from_df <- from_df %>% 
    distinct(entrezgene_id, .keep_all = T) %>% 
    column_to_rownames("entrezgene_id") 

from_vector <- from_df[[1]]
names(from_vector) <- rownames(from_df)
from_vector %>% length()
from_vector %>% head()


to_df <- getBM(attributes = c("entrezgene_id", "mgi_symbol"), 
                 filters = "entrezgene_id", 
                 values = all_path_df[, "to"] %>% unique(), 
                 mart = mmart)
to_df <- to_df %>% 
    distinct(entrezgene_id, .keep_all = T) %>% 
    column_to_rownames("entrezgene_id")

to_vector <- to_df[[1]]
names(to_vector) <- rownames(to_df)
to_vector %>% length()
to_vector %>% head()
```

```{r}
all_path_df$from_symbol <- from_vector[all_path_df$from] 
all_path_df$to_symbol <- to_vector[all_path_df$to]
all_path_df <- all_path_df %>% 
    dplyr::select(from_symbol, to_symbol, from, to, type, subtype)
```

```{r}
all_path_df %>% pull(from_symbol) %>% is.na() %>% table()
all_path_df %>% pull(to_symbol) %>% is.na() %>% table()
```

```{r}
all_path_graph <- graph_from_data_frame(d = all_path_df, 
                                        directed = T)

ego_size(graph = all_path_graph, order = 1, nodes = "P2ry12", mode = "out")
order_1 <- make_ego_graph(graph = all_path_graph, order = 1, nodes = "P2ry12", mode = "out")

plot(order_1[[1]], 
     vertex.size = 15, 
     vertex.frame.color = NA, 
     edge.arrow.size = 0.5)
```

```{r}
ego_size(graph = all_path_graph, nodes = "P2ry12", mode = "out", order = 2)
Gnai1_order1 <- make_ego_graph(graph = all_path_graph, order = 1, nodes = "Gnai1", mode = "out")[[1]]

ll <- layout_nicely(Gnai1_order1)
ll %>% head()
ll %>% range()

pdf(file = "Gnai1_order1.pdf")
plot(Gnai1_order1, 
     vertex.frame.color = NA, 
     vertex.size = 10, 
     vertex.label.cex = 0.5, 
     rescale = F, 
     xlim = range(ll), 
     ylim = range(ll), 
     layout = ll, 
     edge.arrow.size = 0.5)
dev.off()
```


```{r}
vcol <- rep("grey", V(order_2[[1]]) %>% length())
vcol[V(order_2[[1]])$name == "P2ry12"] <- "red"
ll <- layout_with_kk(graph = order_2[[1]])
ll %>% head()
ll %>% range()

pdf(file = "order_2.pdf")
plot(order_2[[1]], 
     vertex.frame.color = NA,
     vertex.size = 20,
     edge.arrow.size = 0.5, 
     rescale = F, 
     xlim = range(ll), 
     ylim = range(ll), 
     layout = ll, 
     vertex.arrow.size = 0.5, 
#     vertex.label = NA, 
     vertex.color = vcol, 
     vertex.label.cex = 0.5)
dev.off()
```




