---
title: "path_selection_with_igraph"
author: "yincy"
date: "4/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
nodes <- read.csv(file = "Dataset1-Media-Example-NODES.csv", header = TRUE, as.is = TRUE)
# the first column is the vertex id, other column trited as vertex attributes

links <- read.csv(file = "Dataset1-Media-Example-EDGES.csv", header = TRUE, as.is = TRUE)
# the first two columns are the vertex ids that this edge between, and the other columns are the edge attributes
```


```{r}
links <- aggregate(x = links[, 3], by = links[, -3], FUN = sum)
```


```{r}
net <- graph_from_data_frame(d = links, 
                             directed = T, 
                             vertices = nodes)
```

```{r}
net
```

```{r}
plot(net, 
     edge.width = E(net)$x / 4)
```


```{r}
all_path_to_s07 <- all_simple_paths(graph = net, 
                                    from = V(net)$name == "s07", 
                                    to = dis_to_s07[1, ][dis_to_s07 == 3] %>% names())
all_path_to_s07[[1]]
```


```{r}
all_path_to_s07 %>% class()
all_path_to_s07_4 <- all_path_to_s07[sapply(all_path_to_s07, length) == 4]
```


```{r}
epath <- E(net)[V(net)[name == "s07"] %->% V(net)[name %in% c("s02", "s06", "s15", "s17")]]
```


```{r}
vcol <- rep("grey", vcount(net))
vcol[V(net)$name %in% (all_path_to_s07_3[[1]] %>% names())] <- "tomato"

ecol <- rep("grey", ecount(net))
ecol[epath] <- "blue"

plot(net, vertex.color = vcol, 
     edge.color = ecol, 
     edge.arrow.size = 0.3)
```


```{r}
edge_list <- get.edgelist(net)
colnames(edge_list) <- c("from", "to")
sub_net <- edge_list %>% as.data.frame() %>% 
    filter(from %in% c(all_path_to_s07_4[[1]] %>% names() %>% .[1:3]), to %in% c(all_path_to_s07_4[[1]] %>% names() %>% .[2:4]))

plot(graph_from_data_frame(sub_net, directed = T), 
     vertex.size = 20, 
     vertex.color = "white", 
     edge.color = "tomato")
```


```{r}
plot_path_distance <- function(net, node_name, degree, node_color){
    require(package = igraph)
    # find all path to a node
    all_path_to_node <- all_simple_paths(graph = net, from = V(net)$name == node_name, to = V(net))
    
    # select path with certain number of nodes, return an list object
    path_distance_of_degree <- all_path_to_node[lapply(all_path_to_node, length) == degree]
    
    # multiple nodes from 2 to degree - 1
    path_distance_nodes_multipled <- lapply(path_distance_of_degree, function(x){
        x <- names(x)
        c(x[1], rep(x[2:(degree - 1)], each = 2), x[degree])
    })
    
    # select edge ids  
    select_edges_ids <- lapply(path_distance_nodes_multipled, FUN = get.edge.ids, graph = net, directed = T)
    
    # select edges along nodes  
    selected_edges_list <- list()
    for(i in 1:length(select_edges_ids)){
        selected_edges_list[[i]] <- E(net)[select_edges_ids[[i]]]
    }
    
    # set edge colors 
    ecol <- rep("grey", ecount(net))
    for(i in 1:length(selected_edges_list)){
        ecol[E(net) %in% selected_edges_list[[i]]] <- "red"
    }
    
    # set vertex color  
    vcol <- rep("grey", vcount(net))
    for(j in 1:length(path_distance_of_degree)){
        vcol[V(net)$name %in% path_distance_of_degree[[j]] %>% names()] <- "tomato"
    }
    
    # set node color for query node
    for(j in 1:length(path_distance_of_degree)){
        vcol[V(net)$name == node_name] <- node_color
    }
    
    # plot the net
    plot(net, 
         vertex.color = vcol, 
         edge.color = ecol, 
         edge.arrow.size = 0.4)
}
plot_path_distance(net = net, node_name = "s07", degree = 3, node_color = "tomato")
```






