---
title: "microarray-data-analysis"
author: "yincy"
date: "10/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 介绍    
实验流程：  
生物学问题 --> 芯片实验设计与实施 --> 预处理(图像分析 image analysis; 表达定量 expression quantification; 标准化 normalization) --> 数据分析(鉴别estimation; 假设检验；聚类分析cluster; 预测prediction ...) --> 实验验证和解释  


为了减少实验产生的噪音，Affy基因芯片在设计时，对每个基因都集成了20组不同的探针，这些特异性探针每个都由25个碱基组成，被称为Perfect Match(PM)探针。与其直接相邻的，也是20组不同探针，这些探针与前面所提的探针序列基本相同，只是正中间的一个碱基被换成了非特异的碱基，理论上来讲，它们应该很难与特异性探针形成相同的阳性结果。而这20组探针被称为MisMatch(MM)探针。有了MM探针，基因芯片就有了阴对内参，可以用于对杂交效果的检测。  


## MAS5 标准化  
MAS5算法是采用了比较直接的策略，任何操作都是简单易懂的。每一块芯片上所有探针的平均值被用于决定尺度因子（scaling factor）。在Bioconductor当中，我们假设每个芯片上所有基因定量后的线性坐标表达值为介于0~200之间的数字，平均值(target)为100。如果有两块芯片我们需要比较，第一块芯片的平均值为50，第二块芯片的平均值为200。那么它们的尺度因子就分别是：2（因为2*50=100）和0.5（因为0.5*200=100）。依照Affymetrix公司的标准，用于比较的芯片之间的尺度因子的比例必须小于3，在这个假设中，2/0.5=4，大于3了，说明两块芯片不能用于比较，其中至少有一块出了问题。  

对于每一块芯片，MAS5算法都会针对每一个目标基因做出所谓P/M/A的分类。所谓P(present)就是PM和MM的值有显著差别，指代该基因被检测到；A(absent)就是PM和MM的值没有显著差别，指代该基因未被检测到；而M(marginal present)就是介于这两者之间的临界状态。如果大部分的基因都未被检测到，说明实验出现了问题。而在多组平行实验中，如果其中一组的被检测到的基因和其它组有显著的差别，那说明该实验可能出现了问题。  

对于每一块芯片，所有的MM值做出统计可以得到背景噪音的平均值，最小值和最大值。如果背景噪音的相对于其它平行组来说平均值过大，那也说明该实验可能出现了问题。而往往高的噪音都伴随着低的被检测到的基因比例(low percentage present)，所以这两个可以做为判断实验是否合格的一个指标。  

因为大部分的细胞都有β-actin和GAPDH，所以Affymetrix在大部分的基因芯片里都将它们设置为一组观察RNA降解程度的内参。针对它们的探针组很好的涵盖了3’至5’的每一个区段。通过比较它们3’相对于中间段或者5’的信号强度，可以很好地指示出实验质量。如果比值很高，那可不是一件好事，这表明不完整β-actin或者GAPDH的存在，说明在标记或者杂交的过程中出现了问题。  

为了验证杂交的质量，Affymetrix公司还加入了一些嵌入探针(spike-in probe)。它们分别是BioB(浓度下限)，BioC，BioD和CreX(浓度上限)。它们的RNA是在标记的过程中加入样品体系的。如果BioB不能被MAS5算法标记为P，说明该芯片的敏感度没有达标。这很有可能是芯片本身的问题。  





