---
title: "ligand_receptor"
author: "yincy"
date: "10/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```
find ligand and recetpor pair between epithelial cell and macrophage  
```

```
data from DIP database 
using data Mmusc20170205.txt.gz; Mmusc20170205CR.txt.gz
```

```{r load packages}
library(tidyverse)
library(biomaRt)
library(readxl)
```


```{r loading data}
m_ppi <- read_tsv(file = "Mmusc20170205.txt.gz")
```


```{r rename columns}
m_ppi <- m_ppi %>% 
  select("id_interactor_a" = `ID interactor A`, 
         "id_interactor_b" = `ID interactor B`,
         "alt_id_interactor_a" = `Alt. ID interactor A`,
         "alt_id_interactor_b" = `Alt. ID interactor B`,
         "alias_interactor_a" = `Alias(es) interactor A`,
         "alias_interactor_b" = `Alias(es) interactor B`,
         "interaction_detection_methods" = `Interaction detection method(s)`,
         "publication_1st_author" = `Publication 1st author(s)`,
         "publication_identifier" = `Publication Identifier(s)`,
         "taxid_interactor_a" = `Taxid interactor A`,
         "taxid_interactor_b" = `Taxid interactor B`,
         "interaction_types" = `Interaction type(s)`,
         "source_databases" = `Source database(s)`,
         "interaction_identifier" = `Interaction identifier(s)`,
         "confidence_value" = `Confidence value(s)`,
         "processing_status" = `Processing Status`)
```


```{r separate into different columns}
m_ppi <- m_ppi %>% 
  filter(taxid_interactor_a == "taxid:10090(Mus musculus)", taxid_interactor_b == "taxid:10090(Mus musculus)") %>% 
    separate(col = id_interactor_a,
             into = c("dip_id_a", "refseq_id_a", "uniprot_id_a"),
             sep = "\\|") %>% 
  separate(col = id_interactor_b,
           into = c("dip_id_b", "refseq_id_b", "uniprot_id_b"),
           sep = "\\|") %>% 
  select(-publication_1st_author, -publication_identifier, -alt_id_interactor_a, -alt_id_interactor_b, -alias_interactor_a, -alias_interactor_b)
```


```{r separate id in different columns}
for(i in 1:dim(m_ppi)[1]){
  if(grepl("uniprot", m_ppi[i, 2], ignore.case = T)){
    m_ppi[i, 3] = m_ppi[i, 2]
    m_ppi[i, 2] = NA
  }
}

for(i in 1:dim(m_ppi)[1]){
  if(grepl("uniprot", m_ppi[i, 5], ignore.case = T)){
    m_ppi[i, 6] = m_ppi[i, 5]
    m_ppi[i, 5] = NA
  }
}

m_ppi <- m_ppi %>% 
  dplyr::select(-source_databases, -taxid_interactor_a, -taxid_interactor_b, -interaction_identifier, -processing_status)
```

```{r replace columns into uniform id}
m_ppi$refseq_id_a <- gsub("refseq:", "", m_ppi$refseq_id_a)
m_ppi$uniprot_id_a <- gsub("uniprotkb:", "", m_ppi$uniprot_id_a)
m_ppi$refseq_id_b <- gsub("refseq:", "", m_ppi$refseq_id_b)
m_ppi$uniprot_id_b <- gsub("uniprotkb:", "", m_ppi$uniprot_id_b)
```

```{r}
unique(m_ppi$uniprot_id_a) %>% length()
```



```{r create mmart object}
mmart <- useEnsembl(biomart = "ensembl", 
                    dataset = "mmusculus_gene_ensembl",
                    mirror = "asia")
```


```{r convert uniprotswissprot protin id to mgi symbol id}
mgi_symbol_a <- getBM(attributes = c("mgi_symbol", "uniprotswissprot"),
                      filters = "uniprotswissprot",
                      values = m_ppi$uniprot_id_a,
                      mart = mmart)
colnames(mgi_symbol_a) <- c("mgi_symbol_a", "uniprotswissprot_a")

mgi_symbol_b <- getBM(attributes = c("mgi_symbol", "uniprotswissprot"),
                     filters = "uniprotswissprot",
                     values = m_ppi$uniprot_id_b,
                     mart = mmart)
colnames(mgi_symbol_b) <- c("mgi_symbol_b", "uniprotswissprot_b")
```


```{r}
m_ppi <- left_join(x = m_ppi, y = mgi_symbol_a, by = c("uniprot_id_a" = "uniprotswissprot_a"))
m_ppi <- left_join(x = m_ppi, y = mgi_symbol_b, by = c("uniprot_id_b" = "uniprotswissprot_b"))

m_ppi <- m_ppi %>% 
  dplyr::select(mgi_symbol_a, mgi_symbol_b, dip_id_a, dip_id_b, uniprot_id_a, uniprot_id_b, interaction_types, interaction_detection_methods, confidence_value) %>% 
  filter(!is.na(mgi_symbol_a), !is.na(mgi_symbol_b))

ind <- duplicated(m_ppi[,1:2])
m_ppi <- m_ppi[!ind, ]
```



## 2016 science  
```{r}
kid_21 <- kidney_macrophage_p21 %>%
  mutate(avg = (kid_mac_p21_1+kid_mac_p21_2)/2) %>% 
  dplyr::select(ensembl, symbol, avg) 
```

```{r}
kid_21_top_2000 <- kid_21 %>% 
  arrange(desc(avg)) %>% 
  top_n(n = 2000)
```

```{r}
write.csv(x = kid_21_top_2000[, 2], file = "kid_top_2000.csv",row.names = F, quote = F)
```



## science 2018  
```{r load 2018 science data}
ep <- read.table(file = "ep.txt")
```

```{r}
write.csv(x = ep,
          file = "epithelial_top_2000.csv",
          row.names = F,
          quote = F)
```


```{r filter by top 3000 genes in epthilial and macrophage}
selected_lr <- m_ppi %>% 
  filter(mgi_symbol_a %in% kid_21_top_3000$symbol | mgi_symbol_b %in% kid_21_top_3000$symbol| mgi_symbol_a %in% ep$symbol | mgi_symbol_b %in% ep$symbol)
```


```{r remove duplicates}
selected_ppi <- read.csv(file = "selected_ppi.csv", stringsAsFactors = F)
```


```{r}
ind <- c()
for(i in 1:dim(selected_ppi)[1]){
  if(tolower(str_trim(selected_ppi[i, 1], side = "both")) == tolower(str_trim(selected_ppi[i, 2], side = "both"))){
    ind = c(ind, i)
  }
}
ind

selected_ppi <- selected_ppi[-ind, ]
```


```{r}
write.csv(x = selected_ppi, file = "selected_ppi.csv", row.names = F, quote = F)
```


```{r}
human_ligang_receptor_pairs <- read.csv(file = "ligand_receptor_pairs.csv", 
                                        stringsAsFactors = F)
```


```{r}
library(biomaRt)
library(magrittr)
```


```{r}
hmart <- useEnsembl(biomart = "ensembl",
                    dataset = "hsapiens_gene_ensembl",
                    mirror = "asia")

mmart <- useEnsembl(biomart = "ensembl",
                    dataset = "mmusculus_gene_ensembl",
                    mirror = "asia")
```

```{r}
human_lr <- c(human_ligang_receptor_pairs$ligand, human_ligang_receptor_pairs$receptor) %>% 
  unique()
```

```{r}
?getLDS
h_to_m <- getLDS(
  attributes = "hgnc_symbol",
  filters = "hgnc_symbol",
  values = human_lr,
  mart = hmart,
  attributesL = "mgi_symbol",
  martL = mmart
)
```

```{r}
write.csv(x = h_to_m, 
          file = "human_to_mouse.csv",
          row.names = F,
          quote = F)
```





