---
title: "Rosalind"
author: "yincy"
date: "6/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Counting DNA Nucleotides  
```{r}
library(magrittr)
library(stringr)

x <- "AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC"
str_split(x, pattern = "") %>% table()
```

2. Transcribing DNA into RNA  
```{r}
dna <- "GATGGAACTTGACTACGTAAATT"
rna <- "GAUGGAACUUGACUACGUAAAUU"

identical(gsub("T", "U", dna), rna)
```

3. Complementing a Strand of DNA  
```{r}
snese <- "AAAACCCGGT"
reverse_anti <- "ACCGGGTTTT"

DNA_pairs <- c("A" = "T", "G" = 'C', "T" = 'A', "C" = "G")
snese %>% 
  str_split(pattern = "", simplify = T) %>% 
  DNA_pairs[.] %>% 
  .[length(.):1] %>% 
  str_c(collapse = "") %>% 
  identical(reverse_anti)


reverse_complement <- function(seq, type){
  require(magrittr)
  require(stringr)
  DNA_paris = c("A" = "T", "T" = "A", "G" = "C", "C" = "G")
  RNA_pairs = c("A" = "U", "U" = "A", "G" = "C", "C" = "G")
  if(toupper(type) == "DNA"){
    seq <- as.character(str_split(seq, pattern = "", simplify = T))
    seq <- as.character(DNA_paris[seq])
    seq <- seq[length(seq):1]
    if(any(is.na(seq))){
      message("there some bases are not recognized as DNA base.\n")
    }
    seq <- str_replace_na(seq, replacement = "*")
    seq <- str_c(seq, collapse = "")
    return(seq)
  }else{
    seq <- as.character(str_split(seq, pattern = "", simplify = T))
    seq <- as.character(RNA_paris[seq])
    seq <- seq[length(seq):1]
    if(any(is.na(seq))){
      message("there some bases are not recognized as RNA base.\n")
    }
    seq <- str_replace_na(seq, replacement = "*")
    seq <- str_c(seq, collapse = "")
    return(seq)
  }
}

sense <- "ACGAUUACN"
reverse_complement(seq = sense, type = "DNA")
```

4. Rabbits and Recurrence Relations  




















