---
title: "directlabels"
author: "yincy"
date: "12/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Polygon methods
```{r}
param.df <- data.frame(
    mean = c(0, 0, 2), 
    sd = c(1, 2, 1)
)

density.df.list <- list()

for(param.i in 1:nrow(param.df)){
  one.param <- param.df[param.i,]
  observation <- seq(-4, 4, by=0.1)
  density.df.list[[param.i]] <- data.frame(
    param.i,
    param.fac=factor(param.i),
    one.param,
    observation,
    density=dnorm(observation, one.param$mean, one.param$sd),
    row.names=NULL)
}

density.df <- do.call(rbind, density.df.list)

library(ggplot2)
gg <- ggplot() +
    geom_line(aes(observation, density, color = param.fac), data = density.df) 

directlabels::direct.label(gg, method = "top.polygons")
```

```{r}
density.df$mean.lab <- paste0("mean=", density.df$mean)
gg <- ggplot() +
  geom_line(aes(observation, density, color = param.fac), data = density.df) +
  directlabels::geom_dl(aes(observation, density, color = param.fac, label.group = param.fac, label = mean.lab), 
                        method = "top.polygons", 
                        data = density.df)
gg
```


```{r}
gg <- ggplot() +
  geom_line(aes(observation, density, color = mean.lab, group = param.fac), 
            data = density.df) 
directlabels::direct.label(gg, method = "top.polygons")
```


```{r}
data(BodyWeight, package = "nlme")
gg <- ggplot() +
  geom_line(aes(Time, weight, color = Rat), 
            data = BodyWeight) +
  facet_grid(. ~ Diet)

gg
```

```{r}
directlabels::direct.label(gg, method = "right.polygons")
```

```{r}
gg.wider <- gg + xlim(-10, 70)
directlabels::direct.label(gg.wider, method = "right.polygons")
```

```{r}
directlabels::direct.label(gg.wider, method = "left.polygons")
```





