---
title: "ggplot2 linetype"
author: "yincy"
date: "11/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
d=data.frame(a=c("a","b","c","d","e","f","g","h", "i", "j", "k", "l"))
ggplot() +
  scale_x_continuous(limits=c(0,1), breaks=NULL, name="") +
  scale_y_discrete(name="") +
  scale_linetype_discrete() +
  geom_segment(data=d, mapping=aes(x=0, xend=1, y=a, yend=a, linetype=a))
```


```{r}
d=data.frame(lt=c("blank", "solid", "dashed", 
                  "dotted", "dotdash", "longdash", 
                  "twodash", "1F", "F1", 
                  "4C88C488", "12345678"))
ggplot() +
  scale_x_continuous(name="", limits=c(0,1), breaks=NULL) +
  scale_y_discrete(name="linetype") +
  scale_linetype_identity() +
  geom_segment(data=d, mapping=aes(x=0, xend=1, y=lt, yend=lt, linetype=lt))

ggsave(filename = "f:/git/R-codes/tidyverse/ggplot2-linetype.tiff")
```



```{r}
lt=c("blank", "solid", "dashed", 
                  "dotted", "dotdash", "longdash", 
                  "twodash", "1F", "F1", 
                  "4C88C488", "12345678")


```










