---
title: "mouse_microphage"
author: "yincy"
date: "9/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r load packages, message=FALSE}
library(Seurat)
library(tidyverse)
library(biomaRt)
```


proteins  
```
TREM-2, IRAK-M, CD206，TGFbR2, TNFAIP3(A20) ，CCR2、CCR7，TNF-a，IL-10
```

protein      | entrez     |mgi_symbol
-------------|------------|------------
TREM-2       | 83433      | Trem2  
IRAK-M       | 73914      | Irak3  
CD206        | 17533      | Mrc1  
TGFbR2       | 21813      | Tgfbr2  
TNFAIP3      | 21929      | Tnfaip3  
CCR2         | 12772      | Ccr2  
CCR7         | 12775      | Ccr7  
TNF-a        | 21926      | Tnf  
IL-10        | 16153      | Il10


genes  
```{r}
mouse_genes <- c("TREM-2" = "83433", "IRAK-M" = "73914", "CD206" = "17533",
                 "TGFbR2" = "21813", "TNFAIP3" = "21929", "CCR2" = "12772",
                 "CCR7" = "12775", "TNF-a" = "21926","IL-10" = "16153")

mouse_gene_symbol <- c("Trem2", "Irak3", "Mrc1", "Tgfbr2", "Ccr2", "Ccr7", "Tnf", "Il10")

mouse_mart <- useEnsembl(biomart = "ensembl", 
                         dataset = "mmusculus_gene_ensembl")

genes <- getBM(attributes = c("mgi_symbol", "ensembl_gene_id", "entrezgene_id"),
               filters = "entrezgene_id",
               values = mouse_genes,
               mart = mouse_mart)
genes <- genes[!duplicated(genes$entrezgene_id), ]
```


```{r pipe workflow, message=FALSE, cache=TRUE, comment=""}
mouse_macrophage <- Read10X(data.dir = "data/") %>% 
    CreateSeuratObject(project = "mouse_macrophage") %>% 
    PercentageFeatureSet(pattern = "^MT-", col.name = "percent.mt") %>% 
    subset(subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5) %>% 
    SCTransform(vars.to.regress = "percent.mt") %>% 
    RunPCA() %>% 
    FindNeighbors(dims = 1:30, verbose = F) %>% 
    FindClusters(dims = 1:30, verbose = F) %>% 
    RunTSNE(dims = 1:30) 
```


```{r find marker gene for each cluster, cache=TRUE}
all_marker_genes <- FindAllMarkers(mouse_macrophage, 
                                   only.pos = F,
                                   logfc.threshold = 0.25,
                                   min.pct = 0.1)

all_marker_genes %>% 
              group_by(cluster) %>% 
              top_n(n = 5, wt = desc(p_val_adj)) %>% 
              dplyr::select(p_val_adj,cluster, gene)
```


visulization  
```{r tsne reduction}
DimPlot(mouse_macrophage, reduction = 'tsne', label = TRUE)
```


```{r feature plot}
table(Idents(mouse_macrophage))
cells = Cells(mouse_macrophage)[Idents(mouse_macrophage) %in% c(0:4)]
for(i in genes$mgi_symbol){
    do.call(what = 'FeaturePlot', 
            args = list(object = mouse_macrophage, features = i, reduction = "tsne", cells = cells))
    ggsave(filename = paste("feature_plot_" ,i, ".tiff", sep = ""))
}
```


```{r violin plot}
for(i in genes$mgi_symbol){
    do.call(what = "VlnPlot",
            args = list(object = mouse_macrophage, features = i, idents = 0:4))
    ggsave(filename = paste('violin_plot_' ,i, ".tiff", sep = ""))
}
```


```{r}
cells = Cells(mouse_macrophage)[Idents(mouse_macrophage) %in% c(0:9)]
FeaturePlot(object = mouse_macrophage, features = "Ccr2", cells = cells)
```




