---
author: "yincy"
date: "1/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r, message=FALSE, warning=FALSE}
library(magrittr)
library(scater)
library(scran)
```

```{r}
sce.kidney <- readRDS("/home/yincy/git/Data/kidney-single-cell/GSE107585/sce.kidney.rds")
sce.kidney <- computeSumFactors(sce.kidney, clusters = sce.kidney$cluster)
sce.kidney <- logNormCounts(x = sce.kidney)

mexper <- tapply(assay(sce.kidney[rownames(sce.kidney) == "Cx3cl1", ], "logcounts"), sce.kidney$celltype, mean, na.rm = T) %>% 
  sort(decreasing = T)

sce.kidney$celltype <- factor(sce.kidney$celltype, levels = names(mexper))

plotExpression(sce.kidney, 
               features = c("Cx3cr1", "Cx3cl1"), 
               x = "celltype", 
               colour_by = "celltype", 
               ncol = 1) +
    scale_fill_discrete(name = NULL, type = c(brewer.pal(9, "Set1"), brewer.pal(7, "Dark2"))) +
    scale_x_discrete(name = NULL) +
    scale_y_continuous(name = "expression") +
    theme(axis.text.x = element_text(angle = -40, hjust = 0), 
          legend.position = "none") 

ggsave("/home/yincy/git/Data/kidney-single-cell/GSE107585/Cx3cr1-Cx3cl1-expression.tiff", 
       width = 10, height = 6)
```



