---
title: "random-sequence"
author: "yincy"
date: "2/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
library(magrittr)
library(stringr)
library(Biostrings)
```

Cebpb
```{r}
cebpb_sense <- "GAAACUUUAGCGAGUCAGA" %>% 
    gsub(pattern = "U", replacement = "T", x = .) %>% 
    DNAString()

freq <- letterFrequency(x = cebpb_sense, letters = c("A", "G", "T", "C"), as.prob = T)

set.seed(111)
Cebpb_control <- sample(x = c("A", "G", "T", "C"), 
                        size = length(cebpb_sense), 
                        replace = T, 
                        prob = freq) %>% 
    str_c(collapse = "")

Cebpb_control %>% DNAString() %>% complement() %>% reverse()
```


P2ry12
```{r}
p2ry12_1_sense <- "CCTTGAACGCCTGCCTTGATCCATT" %>% DNAString()
p2ry12_2_sense <- "CACGAACAGCTTGGCGATGAGGATT" %>% DNAString()

set.seed(222)
p2ry12_control <- c(
    p2ry12_1_sense %>% as.character(), 
    p2ry12_2_sense %>% as.character()
) %>% 
    str_c(collapse = "") %>% 
    DNAString() %>% 
    letterFrequency(x = ., letters = c("A", "G", "T", "C"), as.prob = T) %>% 
    sample(x = c("A", "G", "T", "C"), size = length(p2ry12_1_sense), replace = T, prob = .) %>% 
    str_c(collapse = "") %>% 
    DNAString()
```

```{r}
p2ry12_control %>% complement() %>% reverse()
```



