---
title: "index_fund"
author: "yincy"
date: "2/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE, warning=FALSE}
library(tidyverse)
```


## Clean data
index fund
```{r}
index_fund <- read_csv(file = '/home/yincy/Desktop/zhishu.csv')
index_fund <- index_fund[, 1:17]
index_fund <- index_fund[, c(1:15, 17)]

index_fund$日增长率 <- gsub(pattern = "%", replacement = "", x = index_fund$日增长率)
index_fund$近1周 <- gsub('%', "", index_fund$近1周)
index_fund$近1月 <- gsub("%", "", index_fund$近1月)
index_fund$近3月 <- gsub("%", '', index_fund$近3月)
index_fund$近6月 <- gsub("%", '', index_fund$近6月)
index_fund$近1年 <- gsub("%", '', index_fund$近1年)
index_fund$近2年 <- gsub("%", '', index_fund$近2年)
index_fund$近3年 <- gsub("%", '', index_fund$近3年)
index_fund$今年来 <- gsub("%", '', index_fund$今年来)
index_fund$成立来 <- gsub("%", '', index_fund$成立来)
index_fund$手续费 <- gsub("%", '', index_fund$手续费)

index_fund <- type_convert(df = index_fund, 
             trim_ws = T,
             col_types = "cccdddddddddddddd")

index_fund %>% head()
write.csv(x = index_fund, 
          file = "index_fund.csv",
          row.names = F,
          quote = F)
```


Stock fund
```{r}
stock_fund <- read_csv(file = "/home/yincy/Documents/gupiao.csv")
stock_fund <- stock_fund[, 1:17]
stock_fund <- stock_fund[, c(1:15, 17)]

stock_fund$日增长率 <- gsub(pattern = "%", replacement = "", x = stock_fund$日增长率)
stock_fund$近1周 <- gsub('%', "", stock_fund$近1周)
stock_fund$近1月 <- gsub("%", "", stock_fund$近1月)
stock_fund$近3月 <- gsub("%", '', stock_fund$近3月)
stock_fund$近6月 <- gsub("%", '', stock_fund$近6月)
stock_fund$近1年 <- gsub("%", '', stock_fund$近1年)
stock_fund$近2年 <- gsub("%", '', stock_fund$近2年)
stock_fund$近3年 <- gsub("%", '', stock_fund$近3年)
stock_fund$今年来 <- gsub("%", '', stock_fund$今年来)
stock_fund$成立来 <- gsub("%", '', stock_fund$成立来)
stock_fund$手续费 <- gsub("%", '', stock_fund$手续费)

stock_fund %>% head()
write.csv(x = stock_fund, 
          file = 'stock_fund.csv',
          row.names = F,
          quote = F)
```



