---
title: "neuron microglia"
author: "yincy"
date: "1/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# kv4.3 and Pdgfrb in KEGG pathway  

```{r, message=FALSE}
library(tidygraph)
library(ggraph)
library(igraph)
library(org.Mm.eg.db)
library(tidyverse)
```


```{r}
kegg_pathways <- readRDS(file = "../../P2y12r-and-C1q/data/KEGG/KEGG_pathways_formatted.rds")
names_to_display <- readRDS(file = "../../P2y12r-and-C1q/data/KEGG/names_to_display.rds")
```


```{r}
genes_info <- AnnotationDbi::select(x = org.Mm.eg.db, 
                    keys = c("Kcnd3", "Pdgfrb"), 
                    keytype = "SYMBOL", 
                    columns = c("SYMBOL", "ENTREZID", "ENSEMBL"))
```

Kcnd3 predicted transcription factors PROMO  
```{r}
entrez <- c("YY1" = "22632", 
            "POU2F2" = "18987", 
            "LyF-1" = "22778", 
            "Sp1" = "20683", 
            "RXR-alpha" = "20181", 
            "POU5F1" = "18999", 
            "POU3F1" = "18991", 
            "Pax-5" = "18507", 
            "POU2F1a" = "18986", 
            "RelA" = "19697", 
            "CP2" = "21422", 
            "NF-kappaB1" = "18033", 
            "NF-AT1" = "18019", 
            "TFE3-S" = "209446", 
            "TCF-1(P)" = "21414", 
            "HNF-3" = "14461", 
            "NF-muNR" = "13047", 
            "COE1" = "13591", 
            "HNF-6" = "15379", 
            "Yi" = "67180", 
            "PU.1" = "20375", 
            "Nkx2-1" = "21869", 
            "AhR" = "11622", 
            "MyoD" = "17927", 
            "E2F-1" = "13555", 
            "HNF-3beta" = "15376", 
            "HES-1" = "15205", 
            "AP-1.1" = "16476", 
            "AP-1.2" = "14281", 
            "USF-1" = "22278", 
            "GATA-1" = "14460", 
            "DEC2" = "79362", 
            "c-Rel" = "19696", 
            "myogenin" = "17928", 
            "MTF-1" = "17764", 
            "STAT1" = "20846", 
            "GATA-2" = "14461", 
            "C/EBPalpha" = "12606", 
            "GR" = "14815", 
            "JunD" = "16478", 
            "c-Jun" = "16476", 
            "NF-1.1" = "18027", 
            "NF-1.2" = "18028", 
            "NF-1.3" = "18029", 
            "NF-1.4" = "18032", 
            "NF-AT4" = "18021", 
            "HOXA5" = "15402", 
            "c-Fos" = "14281", 
            "C/EBPbeta" = "12608")

entrez <- entrez %>% as.data.frame() %>% 
    rownames_to_column("PROMO") %>% 
    magrittr::set_colnames(c("PROMO", "ENTREZ"))

tf <- AnnotationDbi::select(org.Mm.eg.db, 
             keys = entrez$ENTREZ, 
             keytype = "ENTREZID", 
             columns = c("SYMBOL", "ENTREZID"))

tf %>% right_join(y = entrez, by = c("ENTREZID" = "ENTREZ"))
```

```{r}
tf_info <- read.table(file = "clipboard", header = F, sep = ";", row.names = NULL)
colnames(tf_info) <- c("PROMO", "Width", "ENSEMBL")
tf_info[, c("PROMO", "ID")] <- str_split(tf_info$PROMO, " \\[", n = 2, simplify = T)
tf_info$ID <- str_replace(tf_info$ID, "\\]$", "")
tf_info 

tf_info <- AnnotationDbi::select(org.Mm.eg.db, 
                  keys = tf_info$ENSEMBL, 
                  keytype = "ENSEMBL", 
                  columns = c("ENSEMBL", "SYMBOL", "ENTREZID")) %>% 
  right_join(tf_info, by = c("ENSEMBL" = "ENSEMBL")) %>% 
  distinct(ENSEMBL, ENTREZID, SYMBOL, .keep_all = T)

tf_info
```

load KEGG pathways  
```{r}
pathways <- readRDS(file = "../../P2y12r-and-C1q/data/KEGG/KEGG_pathways_formatted.rds")
names_to_display <- readRDS(file = "../../P2y12r-and-C1q/data/KEGG/names_to_display.rds")

pathways <- pathways %>% 
  filter(grepl("^[0-9]", from), grepl("^[0-9]", to))
```


Pdgfrb downstream genes  
```{r}
ig <- graph_from_data_frame(d = pathways[, 1:2], directed = T)
dist_to_pdgfrb <- distances(graph = ig, 
                            v = V(ig), 
                            to = V(ig)$name == "18596", 
                            mode = "all", 
                            algorithm = "unweighted") 

dist_to_pdgfrb_genes <- dist_to_pdgfrb %>% 
    as.data.frame() %>% 
    rownames_to_column("entrez") %>% 
    magrittr::set_colnames(c("entrez", "dist")) %>% 
    dplyr::filter(!is.infinite(dist)) %>% 
    dplyr::filter(grepl("^[0-9]", entrez))

tf_downstream_Pdgfrb <- distances(graph = ig, 
                            v = V(ig)$name %in% tf_info$ENTREZID, 
                            to = V(ig)$name == "18596", 
                            mode = "in", 
                            algorithm = "unweighted") %>% 
    as.data.frame() %>% 
    rownames_to_column("entrez") %>% 
    magrittr::set_colnames(c("entrez", "dist_to_pdgfrb")) %>% 
    dplyr::filter(!is.infinite(dist_to_pdgfrb)) %>% 
    dplyr::pull(entrez)

tf_downstream_Pdgfrb <- tf_info[tf_info$ENTREZID %in% tf_downstream_Pdgfrb, ]

# tf_downstream_Pdgfrb %>% 
#   distinct(ENTREZID, SYMBOL) %>% 
#   write.csv(file = "../res/kv4.3_tf_downstream_pdgfrb.csv")
```

```{r}
ego_size(ig, order = 5, nodes = V(ig)$name == "18596")
```

```{r}
paths_to_tf <- shortest_paths(graph = ig, 
               from = V(ig)$name == "18596", 
               to = V(ig)$name %in% tf_downstream_Pdgfrb$ENTREZID)

len <- paths_to_tf$vpath %>% sapply(as_ids) %>% sapply(length)

o1 <- paths_to_tf$vpath %>% sapply(as_ids) %>% sapply("[[", 1) %>% unique()
o2 <- paths_to_tf$vpath %>% sapply(as_ids) %>% sapply("[[", 2) %>% unique()
o3 <- paths_to_tf$vpath %>% sapply(as_ids) %>% sapply("[[", 3) %>% unique()
o4 <- paths_to_tf$vpath %>% sapply(as_ids) %>% .[len > 3] %>% sapply("[[", 4) %>% unique()
o5 <- paths_to_tf$vpath %>% sapply(as_ids) %>% .[len > 4] %>% sapply("[[", 5) %>% unique()
o6 <- paths_to_tf$vpath %>% sapply(as_ids) %>% .[len > 5] %>% sapply("[[", 6) %>% unique()
o7 <- paths_to_tf$vpath %>% sapply(as_ids) %>% .[len > 6] %>% sapply("[[", 7) %>% unique()
```

```{r}
p1 <- pathways %>% 
    dplyr::filter(from %in% o1 & to %in% o2)
p2 <- pathways %>% 
    dplyr::filter(from %in% o2 & to %in% o3)
p3 <- pathways %>% 
    dplyr::filter(from %in% o3 & to %in% o4)
p4 <- pathways %>% 
    dplyr::filter(from %in% o4 & to %in% o5)
p5 <- pathways %>% 
    dplyr::filter(from %in% o5 & to %in% o6)
p6 <- pathways %>% 
    dplyr::filter(from %in% o6 & to %in% o7)


filtered_path <- rbind(p1, p2, p3, p4, p5, p6)
```

```{r}
tf_in_neuron <- readxl::read_xlsx("../res/20210108_result_kv4.3_tf.xlsx", sheet = 1) %>% arrange(PValue) %>% .[, -1]
```

```{r}
neuron <- readxl::read_xlsx("../data/neuron-20210104_rpkm_count.xlsx", 
                            skip = 1, 
                            sheet = 2) 
neuron %>% 
  select(geneid, matches("_label_[0-9]$")) %>% 
  filter(geneid %in% tf_info$SYMBOL)
```


```{r}
ig <- graph_from_data_frame(d = filtered_path, directed = T)
```

```{r}
vc <- rep("gray", length(V(ig)))
vc[V(ig)$name %in% tf_downstream_Pdgfrb$ENTREZID] <- "orange"
vc[V(ig)$name == "18596"] <- "blue"
ll <- layout_nicely(graph = ig)

pdf("../res/Pdgfrb_downstream_tf.pdf")
plot(ig, 
     vertex.size = 5, 
     vertex.color = vc, 
     vertex.label = names_to_display[V(ig)$name], 
     vertex.label.cex = 0.4, 
     vertex.label.dist = 0, 
     vertex.label.color = "black",
     vertex.frame.color = NA, 
     edge.arrow.size = 0.1, 
     edge.label = E(ig)$edge_label, 
     edge.label.cex = 0.5,
     edge.lty = E(ig)$lty,
     layout = ll, 
    # rescale = F, 
    # xlim = ll %>% apply(2, range) %>% .[, 1], 
    # ylim = ll %>% apply(2, range) %>% .[, 2],
    frame = F, 
    edge.width = 0.3
)

dev.off()
```

```{r}
N <- tibble(
    ids = c(filtered_path$from, filtered_path$to) %>% unique()
) %>% 
    mutate(symbol = names_to_display[ids])

E <- filtered_path
E$lty <- factor(E$lty)

g <- tbl_graph(nodes = N, edges = E, directed = T)
```

```{r, message=FALSE, warning=FALSE}
g %>% 
    ggraph(layout = "nicely") +
    geom_edge_link(aes(filter = (.E()$angle == 90), 
                       label = .E()$edge_label, 
                       edge_linetype = .E()$lty), 
                   arrow = arrow(angle = 90, length = unit(1, "mm")), 
                   end_cap = circle(3, "mm"), 
                   edge_width = 0.5, 
                   edge_color = "gray", 
                   show.legend = F) +
    geom_edge_link(aes(filter = (.E()$angle == 30), 
                       label = .E()$edge_label, 
                       edge_linetype = .E()$lty), 
                   arrow = arrow(angle = 30, length = unit(1, "mm")), 
                   end_cap = circle(3, "mm"), 
                   edge_width = 0.5, 
                   edge_color = "gray", 
                   show.legend = F) +
    geom_edge_link(aes(filter = (is.na(.E()$angle)), 
                       label = .E()$edge_label, 
                       edge_linetype = .E()$lty), 
                   arrow = arrow(angle = 30, length = unit(1, "mm")), 
                   end_cap = circle(3, "mm"), 
                   edge_width = 0.5, 
                   edge_color = "gray", 
                   show.legend = F) +
    geom_node_point(size = 5, color = "gold") +
    geom_node_point(aes(filter = (.N()$symbol %in% tf_in_neuron$geneid)), 
                    color = "red", 
                    stroke = 3.5) +
    geom_node_point(aes(filter = (.N()$symbol == "Pdgfrb")), 
               color = "blue", 
               stroke = 3.5) +
    geom_node_text(aes(label = .N()$symbol), size = 3) +
    scale_edge_linetype_manual(name = "", values = c("1" = "solid", "3" = "solid", "5" = "dashed")) +
    theme_graph()

ggsave("../res/tf_signale.pdf")
```


get transcription factor information  
```{r}
definition <- getBM(attributes = c("mgi_symbol", "definition_1006"), 
      filters = "mgi_symbol", 
      values = tf_in_neuron$geneid, 
      mart = mmart)

definition_1006 <- tapply(definition$definition_1006, definition$mgi_symbol, str_c, collapse = ". ")

definition_1006 %>% 
    as.data.frame() %>% 
    rownames_to_column("symbol") %>% 
    magrittr::set_colnames(c("symbol", "definition_1006")) %>% 
    left_join(tf_in_neuron, by = c("symbol" = "geneid")) %>% 
    write.csv("../res/tf_definition.csv", row.names = F)
```



