---
title: "Potassium Channels genes"
author: "yincy"
date: "1/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(org.Mm.eg.db)
library(tidyverse)
```


```{r}
potassium_channels_genes <- c("ENSMUSG00000063142", "ENSMUSG00000002908", 
                              "ENSMUSG00000054477", "ENSMUSG00000000794", 
                              "ENSMUSG00000054342", "ENSMUSG00000058740", 
                              "ENSMUSG00000052726", "ENSMUSG00000031576", 
                              "ENSMUSG00000041248", "ENSMUSG00000041695", 
                              "ENSMUSG00000042529", "ENSMUSG00000044216", 
                              "ENSMUSG00000058743", "ENSMUSG00000026824", 
                              "ENSMUSG00000043301", "ENSMUSG00000038026", 
                              "ENSMUSG00000032034", "ENSMUSG00000044708", 
                              "ENSMUSG00000062609", "ENSMUSG00000051497", 
                              "ENSMUSG00000030247", "ENSMUSG00000096146", 
                              "ENSMUSG00000079436", "ENSMUSG00000033998", 
                              "ENSMUSG00000037624", "ENSMUSG00000049265", 
                              "ENSMUSG00000024957", "ENSMUSG00000023243", 
                              "ENSMUSG00000046410", "ENSMUSG00000024936", 
                              "ENSMUSG00000036760", "ENSMUSG00000033854", 
                              "ENSMUSG00000050138", "ENSMUSG00000045404", 
                              "ENSMUSG00000035238", "ENSMUSG00000023387", 
                              "ENSMUSG00000040901", "ENSMUSG00000047976", 
                              "ENSMUSG00000040724", "ENSMUSG00000047959", 
                              "ENSMUSG00000042604", "ENSMUSG00000045534", 
                              "ENSMUSG00000038077", "ENSMUSG00000038201", 
                              "ENSMUSG00000042861", "ENSMUSG00000050556", 
                              "ENSMUSG00000030525", "ENSMUSG00000058975", 
                              "ENSMUSG00000035681", "ENSMUSG00000062785", 
                              "ENSMUSG00000027895", "ENSMUSG00000009731", 
                              "ENSMUSG00000060882", "ENSMUSG00000040896", 
                              "ENSMUSG00000051726", "ENSMUSG00000074575", 
                              "ENSMUSG00000059852", "ENSMUSG00000045053", 
                              "ENSMUSG00000045246", "ENSMUSG00000009545", 
                              "ENSMUSG00000016346", "ENSMUSG00000056258", 
                              "ENSMUSG00000028631", "ENSMUSG00000028033", 
                              "ENSMUSG00000022342", "ENSMUSG00000047298", 
                              "ENSMUSG00000040164", "ENSMUSG00000050963", 
                              "ENSMUSG00000043673", "ENSMUSG00000058248", 
                              "ENSMUSG00000034402", "ENSMUSG00000038319", 
                              "ENSMUSG00000001901", "ENSMUSG00000059742", 
                              "ENSMUSG00000035580", "ENSMUSG00000037579", 
                              "ENSMUSG00000035355")

length(potassium_channels_genes)

potassium_channels_genes_info <- AnnotationDbi::select(org.Mm.eg.db, 
                                        keys = potassium_channels_genes, 
                                        keytype = "ENSEMBL", 
                                        columns = c("ENSEMBL", "ENTREZID", "SYMBOL"))

write.csv(x = potassium_channels_genes_info, 
          file = "../data/potassium_channel_genes.csv", 
          row.names = F, 
          quote = F)
```




