---
title: "neuron microglia data preprocessing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(scran)
library(scater)
library(DropletUtils)
library(data.table)
library(nichenetr)
library(EnsDb.Mmusculus.v79)
```

# dataset 1
From zhuang's paper [PMID:30385464], GSE113576  

```{r}
GSE113576 <- read10xCounts(samples = "../../../../Data/Brain/GSE113576/data", 
                           sample.names = "zhuang-brain-sc", 
                           type = "sparse", 
                           col.names = T)
GSE113576 %>% colData()
GSE113576 %>% rownames() %>% head
GSE113576 %>% colnames() %>% head
# fwrite(x = counts(GSE113576) %>% as.matrix(), 
#        file = "../../../../Data/Brain/GSE113576/GSE113576_counts_matrix.csv", 
#        sep = ",", 
#        col.names = T, 
#        quote = F, row.names = T)

cell_meta <- readxl::read_xlsx("../../../../Data/Brain/GSE113576/aau5324_Moffitt_Table-S1.xlsx", 
                               skip = 1, 
                               col_names = T) %>%
  dplyr::rename(CellID = `Cell name`, "Replicate" = `Replicate number`, 
         CellClass = `Cell class (determined from clustering of all cells)`, 
         SubClass_non_neuron = `Non-neuronal cluster (determined from clustering of all cells)`, 
         SubClass_neuron = `Neuronal cluster (determined from clustering of inhibitory or excitatory neurons)`) %>% 
  dplyr::mutate(SubClass_neuron = ifelse(is.na(SubClass_neuron), "", SubClass_neuron), 
         SubClass_non_neuron = ifelse(is.na(SubClass_non_neuron), "", SubClass_non_neuron),
         SubClass = paste(SubClass_neuron, SubClass_non_neuron, sep = "")) %>% 
  dplyr::select(-SubClass_neuron, -SubClass_non_neuron) %>% 
  as.data.frame()
rownames(cell_meta) <- cell_meta$CellID

feature_meta <- data.frame(ensembl = rownames(GSE113576))
feature_meta$symbol <- mapIds(EnsDb.Mmusculus.v79, 
                              keys = feature_meta$ensembl, 
                              keytype = "GENEID", 
                              column = "SYMBOL")
rownames(feature_meta) <- feature_meta$ensembl
feature_meta$symbol <- convert_mouse_to_human_symbols(feature_meta$symbol)
feature_meta <- feature_meta %>% 
  dplyr::filter(!is.na(symbol))
feature_meta <- feature_meta[!duplicated(feature_meta$symbol), ]


mat <- counts(GSE113576) 
# mat <- fread("../../../../Data/Brain/GSE113576/GSE113576_counts_matrix.csv", 
#              sep = ",")

mat <- mat %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column("ensembl") %>% 
  left_join(feature_meta, by = c("ensembl" = "ensembl")) %>% 
  dplyr::select(ensembl, symbol, everything()) %>% 
  dplyr::filter(!is.na(symbol))

mat <- mat[!duplicated(mat$symbol), ]
rownames(mat) <- mat$symbol
mat <- mat[, -c(1, 2)]

write.csv(x = cell_meta, 
          file = "../../../../Data/Brain/GSE113576/cell_meta.csv")
write.csv(x = feature_meta, 
          file = "../../../../Data/Brain/GSE113576/feature_meta.csv")
write.csv(x = cell_meta[, c(1, 5)], 
          file = "../../../../Data/Brain/GSE113576/cell_meta-cc.csv", 
          row.names = F, 
          quote = F)
```

```{r}
sce.GSE113576 <- SingleCellExperiment(assays = list(counts = mat %>% as.matrix()), 
                                      rowData = feature_meta, 
                                      colData = cell_meta)

sce.GSE113576 <- computeSumFactors(sce.GSE113576, clusters = sce.GSE113576$CellClass)
sce.GSE113576 <- logNormCounts(sce.GSE113576)
saveRDS(object = sce.GSE113576, 
        file = "../../../../Data/Brain/GSE113576/sce.GSE113576-normalized.rds")
sce.GSE113576 <- readRDS("../../../../Data/Brain/GSE113576/sce.GSE113576.rds")
```

```{r}
GSE113576.logcounts <- fread("../../../../Data/Brain/GSE113576/GSE113576.logcounts.csv", 
                             sep = ",", 
                             stringsAsFactors = F, 
                             data.table = F, 
                             nThread = 10)
GSE113576.logcounts <- GSE113576.logcounts %>% dplyr::rename("ensembl" = "V1")

GSE113576.logcounts[1:10, 1:10]

mgs <- GSE113576.logcounts[, "ensembl", drop = T]
df <- data.frame(ensembl = mgs)
df$symbol <- mapIds(EnsDb.Mmusculus.v79, 
                    keys = df$ensembl, 
                    keytype = "GENEID", 
                    column = "SYMBOL")

GSE113576.logcounts <- GSE113576.logcounts %>%  
    left_join(df, by = c("ensembl" = "ensembl")) %>% 
    dplyr::select(symbol, everything()) 

# convert mouse symbol to human symbol
GSE113576.logcounts$symbol <- convert_mouse_to_human_symbols(GSE113576.logcounts$symbol)
GSE113576.logcounts <- GSE113576.logcounts[!is.na(GSE113576.logcounts$symbol), ]

# remove duplicated symbol rows
GSE113576.logcounts <- GSE113576.logcounts[!duplicated(GSE113576.logcounts$symbol), ]

fwrite(x = GSE113576.logcounts[, -2], 
       file = "../../../../Data/Brain/GSE113576/GSE113576.logcounts-human-symbol.csv", 
       sep = ",", 
       row.names = F,
       quote = F)
```


# dataset 2
from GSE60361  

```{r}
library(scRNAseq)
library(scran)
library(scater)

sce.zeisel <- ZeiselBrainData()
sce.zeisel <- sce.zeisel[, !(sce.zeisel$level2class == "(none)")]
# saveRDS(object = sce.zeisel, file = "../../../../Data/Brain/GSE60361/sce.zeisel.rds")
sce.zeisel <- computeSumFactors(sce.zeisel, clusters = sce.zeisel$level1class)
sce.zeisel <- logNormCounts(x = sce.zeisel)

sce.zeisel.logcounts <- logcounts(sce.zeisel)

sce.zeisel.logcounts <- sce.zeisel.logcounts %>% 
  as.data.frame() %>% 
  rownames_to_column("symbol")

sce.zeisel.logcounts$symbol <- convert_mouse_to_human_symbols(sce.zeisel.logcounts$symbol)
sce.zeisel.logcounts <- sce.zeisel.logcounts[!is.na(sce.zeisel.logcounts$symbol), ]
sce.zeisel.logcounts[1:5, 1:5]
fwrite(x = sce.zeisel.logcounts, 
       file = "../../../../Data/Brain/GSE60361/zeisel.logcounts-human-symbol.csv", 
       sep = ",", 
       quote = F, 
       row.names = F)

cell_meta <- colData(sce.zeisel) %>% 
  as.data.frame() %>% 
  dplyr::select(cell_id, level2class)

write.csv(x = cell_meta, 
          file = "../../../../Data/Brain/GSE60361/zeisel.cell-meta.csv", 
          row.names = F, 
          quote = F)
```

