---
title: "HIF regulators"
author: "yincy"
date: "7/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(nichenetr)
library(tidyverse)
```


```{r}
weighted_network <- readRDS(file = "/home/yincy/git/Data/NicheNet/data/weighted_networks.rds")
ligand_tf_matrix <- readRDS(file = "/home/yincy/git/Data/NicheNet/data/ligand_tf_matrix.rds")

lr_network <- readRDS(file = "/home/yincy/git/Data/NicheNet/data/lr_network.rds")
sig_network <- readRDS(file = "/home/yincy/git/Data/NicheNet/data/signaling_network.rds")
gr_network <- readRDS(file = "/home/yincy/git/Data/NicheNet/data/gr_network.rds")
```


```{r}
ligands <- lr_network %>% pull(from) %>% unique()

targets_all <- ligand_tf_matrix %>% rownames() %>% unique()

targets <- grep("HIF", targets_all, value = T, ignore.case = T)

active_signaling_network <- get_ligand_signaling_path(
    ligand_tf_matrix = ligand_tf_matrix, 
    ligands_all = ligands, 
    targets_all = targets, 
    weighted_networks = weighted_network
)

active_signaling_network_min_max <- active_signaling_network

active_signaling_network_min_max$sig <- active_signaling_network_min_max$sig %>% 
    mutate(weight = (weight - min(weight)) / (max(weight) - min(weight)) + 0.75)

active_signaling_network_min_max$gr <- active_signaling_network_min_max$gr %>% 
    mutate(weight = (weight - min(weight)) / (max(weight) - min(weight)) + 0.75)


graph_min_max <- diagrammer_format_signaling_graph(
    signaling_graph_list = active_signaling_network_min_max, 
    ligands_all = ligands, 
    targets_all = targets, 
    gr_color = "steelblue", 
    sig_color = "indianred"
)

DiagrammeR::render_graph(graph_min_max, layout = "tree")
```


```{r, message=FALSE, warning=FALSE}
library(igraph)

net_HIF1A <- graph_from_data_frame(d = active_signaling_network_min_max$gr %>% 
                                       filter(to == "HIF1A", weight > 1.2), 
                                   directed = T, 
                                   vertices = active_signaling_network_min_max$gr %>% 
                                       filter(to == "HIF1A", weight > 1.2) %>% pull(to) %>% 
                                       append(values = active_signaling_network_min_max$gr %>% 
                                                  filter(to == "HIF1A", weight > 1.2) %>% pull(from)) %>% unique())
net_HIF1A


ll <- layout_with_fr(graph = net_HIF1A)
l = 1
ll <- igraph::norm_coords(layout = ll, xmin = -l, ymin = -l, xmax = l, ymax = l)
```

```{r}
pdf(file = "/home/yincy/git/R-codes/tumor/HIF1A_gr.pdf")
plot(net_HIF1A, 
     vertex.size = 5, 
     vertex.label.cex = 1, 
     layout = ll, 
     rescale = T, 
     edge.width = E(net_HIF1A)$weight/min(E(net_HIF1A)$weight) * 2, 
     vertex.shape = "none")
dev.off()
```



```{r}
active_signal_network$gr %>% pull(to) %>% unique()
```

```{r}
HIF1A_regulators <- active_signal_network$gr %>% 
    filter(to == "HIF1A") %>% 
    arrange(-weight) %>% 
    pull(from) %>% 
    unique()
```


```{r}
HIF3A_regulators <- active_signal_network$gr %>% 
    filter(to == "HIF3A") %>% 
    arrange(-weight) %>% 
    pull(from) %>% 
    unique()
```

```{r}
HIF1A_AS2_regulators <- active_signal_network$gr %>% 
    filter(to == "HIF1A-AS2") %>% 
    arrange(-weight) %>% 
    pull(from) %>% 
    unique()
```


```{r}
HIF1AN_regulators <- active_signal_network$gr %>% 
    filter(to == "HIF1AN") %>% 
    arrange(-weight) %>% 
    pull(from) %>% 
    unique()
```


```{r}
df <- data.frame(
    HIF1A = HIF1A_regulators %>% head(n = 10), 
    HIF3A = HIF3A_regulators %>% head(n = 10), 
    HIF1AN = HIF1AN_regulators %>% head(n = 10), 
    `HIF1A-AS2` = HIF1A_AS2_regulators %>% head(n = 10)
)
DT::datatable(df)
```

```{r}
overlap <- calculate.overlap(x = list(HIF1A = HIF1A_regulators, 
                                      HIF3A = HIF3A_regulators, 
                                      HIF1AN = HIF1AN_regulators, 
                                      HIF1A_AS2 = HIF1A_AS2_regulators))

overlap[[1]] %>% matrix(nrow = 4, byrow = T) %>% DT::datatable()
```

```{r}
venn.diagram(x = list(HIF1A = HIF1A_regulators, 
                      HIF3A = HIF3A_regulators, 
                      HIF1AN = HIF1AN_regulators, 
                      HIF1A_AS2 = HIF1A_AS2_regulators), 
             filename = "HIF_Venn.tiff")
```


```{r}
listAttributes(mart = hmart)
```


```{r}
gene_mart <- getBM(attributes = c("gene_biotype", "entrezgene_description", "hgnc_symbol"), 
                   filters = "entrezgene_id", 
                   values = genes_entrez, 
                   mart = hmart)

gene_mart
```


```
hypoxia, anoxia; anoxic; oxygen deficit; oxygen deficiency; oxygen deprivation
```

```{r}
hypoxia_index <- grepl(pattern = "hypoxia|anoxia|anoxic|oxygen deficiency|oxygen deprivation|oxygen deficit", 
                       x = gene_mart$entrezgene_description, 
                       ignore.case = T)
gene_mart[hypoxia_index, ] %>% .[, 2:3] %>% DT::datatable()
```



## GO annotation  
```{r}
library(GO.db)

GO.db %>% class()
methods(class = "GODb")
```
  
```{r}
GO_term <- GO.db::GOTERM %>% as.data.frame()

GO_term %>% 
    filter(Definition %in% "hypoxia|anoxia|anoxic|oxygen deficiency|oxygen deprivation|oxygen deficit")

hypoxia_go_id <- GO_term[grepl("hypoxia|anoxia|anoxic|oxygen deficiency|oxygen deprivation|oxygen deficit", GO_term$Definition), ] %>% 
    .[, -1] %>% 
    pull(go_id) %>% unique()

getBM(attributes = c("hgnc_symbol"), 
      filters = "go", 
      values = hypoxia_go_id, 
      mart = hmart)
```

```{r}
listFilters(hmart)
```


