---
title: "Control-AMD-bulk-analysis"
author: "yincy"
date: "4/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# load package  
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(edgeR)
library(limma)
library(biomaRt)
library(GEOquery)
library(EnsDb.Hsapiens.v86)
library(RColorBrewer)
```


# get sample metadata  
```{r, cache=TRUE, cache.path="."}
GSE135092 <- getGEO(GEO = "GSE135092")
RPE_AMD_sample_info <- GSE135092[[1]] %>% pData() %>% 
    dplyr::filter(`tissue:ch1` == "RPE, Macula", `amd_status:ch1` == 'AMD') %>% 
    dplyr::select(title, geo_accession, `tissue:ch1`, organism_ch1, characteristics_ch1, characteristics_ch1.1, `amd_status:ch1`)

RPE_Control_sample_info <- GSE135092[[1]] %>% pData() %>% 
    dplyr::filter(`tissue:ch1` == "RPE, Macula", `amd_status:ch1` == "Control") %>% 
    dplyr::select(title, geo_accession, `tissue:ch1`, organism_ch1, characteristics_ch1, characteristics_ch1.1, `amd_status:ch1`)
```
 

# load data  
```{r}
amd_geo_accession <- readRDS(file = "AMD_geo_accession.rds")
control_geo_accession <- readRDS(file = "Control_geo_accession.rds")

amd_ctl_reads <- readRDS(file = "normal_amd_reads_count_table.rds")
amd_ctl_reads %>% dim()
amd_ctl_reads %>% .[1:5, 1:5]
```

```{r}
quantile(x = amd_ctl_reads, probs = seq(0, 1, 0.1))
```


```{r}
identical(x = colnames(amd_ctl_reads), 
          y = c(RPE_Control_sample_info$geo_accession, RPE_AMD_sample_info$geo_accession))
```


## filtering low expressed genes  
```{r library size plot}
colSums(amd_ctl_reads) %>% barplot(names.arg = NA)
abline(h = colSums(amd_ctl_reads) %>% median(), col = "blue")
```


# Convert counts to DGEList  
```{r}
sample_info <- rbind(RPE_Control_sample_info, RPE_AMD_sample_info)
group <- rep(c("Control", "AMD"), c(105, 26))

y <- DGEList(counts = amd_ctl_reads, 
             samples = sample_info, 
             group = group)
```


```{r}
y$counts %>% .[1:5, 1:5]
```

```{r}
y$samples
```

## filter out low expressed genes  
```{r calculate normalization factors}
y <- calcNormFactors(object = y, 
                     method = "TMM")
```

```{r}
barplot(y$samples$norm.factors, col = "orange", border = NA, ylim = c(0, 1.3))
abline(h = c(0.8, 1, 1.2), col = "red", lty = 2, lwd = 1)
```


```{r cpm normalize}
cpm_reads <- edgeR::cpm(y = y, 
                normalized.lib.size = T)
```


```{r}
keep <- rowSums(cpm_reads > 0.5) > length(c(RPE_AMD_sample_info$geo_accession, RPE_Control_sample_info)) * 0.4
y_keep <- y[keep, ]
```


```{r}
plotMDS(y_keep, pch = c(1, 4)[y$samples$group], col = RColorBrewer::brewer.pal(n = 3, name = "Set1")[1:2][y$samples$group])
legend("topleft", legend = y$samples$group %>% unique(), 
       col = RColorBrewer::brewer.pal(n = 3, name = "Set1")[1:2][y$samples$group %>% unique()], 
       pch = c(1, 4)[y$samples$group %>% unique()])
```

```{r}
boxplot(log2(cpm_reads[keep, ] + 0.025),
        col = c("orange", "blue")[y$samples$group], 
        xaxt = "n", 
        main = "log2 cpm expression")
abline(h = log2(cpm_reads[keep, ] + 0.025) %>% median(), lty = 2, lwd = 1, col = "red")
```



# differential expression analysis 
```{r}
design <- model.matrix( ~ 0 + group)
colnames(design) <- gsub("group", "", colnames(design))
```


```{r}
v <- voom(counts = y_keep, design = design, plot = T)
```

```{r}
boxplot(v$E, xaxt = "n", col = c("orange", "blue")[y$samples$group])
abline(h = v$E %>% median(), lty = 2, lwd = 1, col = "red")
```

```{r}
fit <- lmFit(object = v)
names(v)
```


```{r}
cont_mat <- makeContrasts(AMD.vs.Control = AMD - Control, levels = design)
fit_cont <- contrasts.fit(fit = fit, contrasts = cont_mat)
fit_cont <- eBayes(fit = fit_cont)
dim(fit_cont)
summ_fit <- decideTests(object = fit_cont)
summary(summ_fit)
```


## KEGG and GO  
```{r}
degs <- fit_cont %>% as.data.frame() %>% subset(p.value <= 0.05) %>% rownames()
```


```{r}
degs_genes <- select(x = EnsDb.Hsapiens.v86, 
       keys = degs, 
       column = c("GENEID", "ENTREZID"), 
       keytype = "GENEID")
```

```{r}
go <- goana(de = degs_genes$ENTREZID, species = "Hs")
go[order(go$P.DE), ]
```


```{r}
ke <- kegga(de = degs_genes$ENTREZID)
ke[order(ke$P.DE), ]
```

```{r}
altered_paths <- ke[order(ke$P.DE), ] %>% head(n = 30) %>% rownames()
```

```{r}
source("f:/git/R-codes/my-functions/kegg-pathways.R")
```

```{r}
hsa_path <- KEGG_Pathways(database = "pathway", organism = "hsa")
hsa_path %>% names()
```


```{r}
path_name <- keggList("pathway", "hsa")
path_name[altered_paths]
```


## Metabolomics  

```{r}
metabolites <- read.csv(file = "f:/metabolites.csv", stringsAsFactors = F)
metabolites %>% 
    dplyr::filter(tolower(Sub.Pathway) == "tyrosine metabolism")
```

```{r}
intersect(x = metabolites %>% dplyr::filter(Qval.Sig == 1) %>% pull(Sub.Pathway) %>% tolower(), 
          y = ke[order(ke$P.DE), ] %>% dplyr::filter(P.DE <= 0.05) %>% pull(Pathway) %>% tolower())
```

## Tyrosine metabolism  
```{r}
tyrosine_metabolism_genes <- keggLink("hsa", "path:hsa00350")
tyrosine_metabolism_genes <- gsub("hsa:", "", tyrosine_metabolism_genes)
names(tyrosine_metabolism_genes) <- NULL
inter_genes <- intersect(tyrosine_metabolism_genes, degs_genes$ENTREZID)
inter_genes <- degs_genes[degs_genes$ENTREZID %in% inter_genes, ]
```

```{r}
inter_cpm <- cpm_reads[rownames(cpm_reads) %in% inter_genes$GENEID, ]

g_data <- apply(inter_cpm, 1, median)
names(g_data) <- inter_genes$ENTREZID

ann_col = data.frame(group = rep(c("Control", "AMD"), c(length(control_geo_accession), length(amd_geo_accession))))
rownames(ann_col) <- c(control_geo_accession, amd_geo_accession)

pheatmap::pheatmap(mat = inter_cpm, 
                   annotation_col = ann_col, 
                   clustering_method = "ward.D2", 
                   show_colnames = F, 
                   main = "variable genes in tyrosine metabolism")
```


```{r}
library(pathview)
pathview(gene.data = g_data, 
         cpd.data = c("C09368", "C01179"), 
         pathway.id = "hsa00350")
```


## gene set enrichment  
```{r}
library(fgsea)
library(qusage)
c2 <- read.gmt(file = "c:/Users/YinCY/Desktop/c2.all.v7.1.entrez.gmt")
```

```{r}
stats <- cpm_reads[rownames(cpm_reads) %in% degs, ]
stats <- apply(stats[, amd_geo_accession], 1, mean) / apply(stats[, control_geo_accession], 1, mean)
name_stats <- names(stats)

name_entrez <- c()
for(i in 1:dim(degs_genes)[1]){
    if(degs_genes[i, "GENEID"] %in% name_stats){
        name_entrez[i] <- degs_genes[i, "ENTREZID"]
    }
}

df <- as.data.frame(stats)
df <- rownames_to_column(df, "GENEID")

entrez <- select(EnsDb.Hsapiens.v86, 
       keys = names(stats), 
       keytype = "GENEID", 
       column = c("ENTREZID", "GENEID"))

df <- left_join(df, entrez, by = "GENEID")
df <- na.omit(df)
df <- df[!duplicated(df$ENTREZID), ]
df
rownames(df) <- df$ENTREZID
df <- df[, 1]
stats <- df[, 3]
names(stats) <- df$ENTREZID

amd_set <- fgsea(pathways = c2, 
                 stats = stats, 
                 nperm = 1000)
amd_set %>% 
    arrange(padj)
```



