---
title: "migration"
author: "yincy"
date: "12/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```


```{r load packages}
library(tidyverse)
library(biomaRt)
library(KEGGREST)
library(readxl)
library(magrittr)
```


```{r read in data}
dc <- read_xlsx(path = "reads-counts.xlsx")
dc <- dc[, -1]
colnames(dc) <- c("Symbol", "ATP_3uM", "ATP_3uM+inh", "ATP_500uM", "Control")
```


```{r cpm normalize}
lib.size <- colSums(dc[, -1])
dc[,2:5] <- apply(dc[, 2:5], 2, function(x){(x * 1e6) / lib.size})
```

```{r filtering}
index <- c()
for(i in 1:dim(dc)[1]){
  index <- c(index, sum(dc[i, 2:5] >= 1) >= 2)
}
```


```{r}
dc <- dc[index, ]
```


```{r}
dc <- dc %>% 
    mutate(atp.3_vs_ctl_fc = ATP_3uM / Control)
```


```{r}
fc3_3_vs_ctl <- dc %>% 
    filter(atp.3_vs_ctl_fc >= 3 | atp.3_vs_ctl_fc <= 1/3) %>% 
    .[, 1, drop = T]
```

```{r}
migration <- dc[dc$Symbol %in% fc3_3_vs_ctl, ]
```



```{r}
mmart <- useEnsembl(biomart = "ensembl", dataset = "mmusculus_gene_ensembl")
```

```{r}
listAttributes(mmart, page = "feature_page")
```


```{r}
genes <- getBM(attributes = c("name_1006", "namespace_1003", "mgi_symbol"),
               filters = "mgi_symbol",
               values = migration$Symbol,
               mart = mmart)
```

```{r}
BP_genes <- genes %>% 
    filter(namespace_1003 == "biological_process") 
```


```{r}
movement_index <- grepl(pattern = "migration|movement|localization|motility", 
      x = BP_genes$name_1006, ignore.case = T) 

movement_index %>% table()
```


```{r}
movement_genes <- BP_genes[movement_index, ] %>% .[, 3] %>% unique()
```


```{r}
migration$related_to_movement <- ifelse(migration$Symbol %in% movement_genes, "Yes", "No")
```



```{r}
write.csv(x = migration %>% arrange(desc(atp.3_vs_ctl_fc)), 
          file = "3um ATP vs Control FC3.csv",
          row.names = F,
          quote = F)
```

