---
title: "ggplot2-vertical-intervals"
author: "yincy"
date: "5/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
```

```{r}
df <- data.frame(
  trt = factor(c(1, 1, 2, 2)),
  resp = c(1, 5, 3, 4),
  group = factor(c(1, 2, 1, 2)),
  upper = c(1.1, 5.3, 3.3, 4.2),
  lower = c(0.8, 4.6, 2.4, 3.6)
)
```

```{r}
p <- ggplot(df, aes(trt, resp, colour = group))

p + geom_linerange(aes(ymin = lower, ymax = upper))
```

```{r}
p + geom_pointrange(aes(ymin = lower, ymax = upper))
```

```{r}
p + geom_crossbar(aes(ymin = lower, ymax = upper), width = 0.1)
```

```{r}
p + geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.1)
```

```{r}
p + 
    geom_line(aes(group = group)) +
    geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.1)
```

If you want to dodge bars and errorbars, you need to manually specify the dodge width  

```{r}
p <- ggplot(df, aes(trt, resp, fill = group)) 

dodge <- position_dodge(width = 0.9)
p + 
    geom_errorbar(aes(ymin = lower, ymax = upper, colour = group), 
                  width = 0.2, 
                  position = dodge) +
    geom_col(position = dodge) 
```


