---
title: "ggplot2-stats"
author: "yincy"
date: "9/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Stat
A statistical transformation, transforms the data, typically by summarising it in some manner.   


## stats associated with geom function  

- `stat_bin()`: `geom_bar()`, `geom_freqpoly()`, `geom_histogram()`  
- `stat_bin2d()`: `geom_bin2d()`  
- `stat_bindot()`: `geom_dotplot()`  
- `stat_binhex()`: `geom_hex()`  
- `stat_boxplot()`: `geom_boxplot()`  
- `stat_contour()`: `geom_comtour()`  
- `stat_quantile()`: `geom_quantile()`  
- `stat_smooth()`: `geom_smooth()`  
- `stat_sum()`: `geom_count()`  


## stats doesn't associated with geom function  
- `stat_ecdf()`: compute a empirical cumulative distribution plot.  
- `stat_function()`: compute y values from a function of x values.  
- `stat_summary()`: summarise y value at distinct x values.  
- `stat_summary2d()`, `stat_summary_hex()`: summarise binned values.  
- `stat_qq()`: perform calculations for a quantile-quantile plot.  
- `stat_spoke()`: convert angle and radius to position.  
- `stat_unique()`: remove duplicated rows.  

There are two ways to use these functions. You can either add a `stat_()` function and override the default geom, or add a `geom_()` function and override the default stat.  

Internally, a stat takes a data frame as input and returns a data frame as output, and so a stat can add new variables to the original dataset. It is possible to map aesthetics to these new variables. For example, `stat_bin`, the statistic used to make histograms, produces the following variables:  

- `count`, the number of observations in each bin.  
- `density`, the density of observations in each bin (percentage of total/bar width)  
- `x`, the center of the bin  







