---
title: "ggplot2-programming"
author: "yincy"
date: "12/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Single Components

```{r}
geom_lm <- function(formula = y ~ x, 
                    colour = alpha("steelblue", 0.5), 
                    size = 2, ...){
    geom_smooth(formula = formula, 
                se = FALSE, 
                method = "lm", 
                colour = colour, 
                size = size, ...)
                    }

ggplot(mpg, aes(displ, 1/hwy)) +
    geom_point() +
    geom_lm()

ggplot(mpg, aes(displ, 1 / hwy)) +
    geom_point() +
    geom_lm(formula = y ~ poly(x, 2), size = 1, colour = "red")
```

```{r}
hit <- geom_histogram(data = NULL, 
                      bins = 100, 
                      fill = "pink")

ggplot(mtcars, aes(mpg)) +
    hit
```

```{r}
hitblue <- geom_histogram(
    data = NULL, 
    bins = 30, 
    fill = colorRampPalette(colors = RColorBrewer::brewer.pal(n = 9, name = "Blues"))(30)
)

ggplot(mtcars, aes(mpg)) +
    hitblue
```

# Multiple Components

**ggplot2** has a convenient way of adding multiple components to a plot in one step with a list.  

```{r}
geom_mean <- function(){
    list(
        stat_summary(fun.y = "mean", geom = "bar", fill = "grey70"), 
        stat_summary(fun.data = "mean_cl_normal", geom = "errorbar", width = 0.4)
    )
}

ggplot(mpg, aes(class, cty)) + geom_mean()
ggplot(mpg, aes(drv, cty)) + geom_mean()
```

```{r}
geom_mean <- function(se = TRUE){
    list(
        stat_summary(fun = "mean", geom = "bar", fill = "grey70"), 
        if(se){
            stat_summary(fun.data = "mean_cl_normal", geom = "errorbar", width = 0.4)
        }
    )
}

ggplot(mpg, aes(drv, cty)) + geom_mean(se = T)
ggplot(mpg, aes(drv, cty)) + geom_mean(se = F)
```



















