---
title: "C1q-C3"
author: "yincy"
date: "10/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
```


# C1q and C3 regulators   
```{r}
mgs <- genes(EnsDb.Mmusculus.v79)

C1q <- mgs[grep("^C1q", mgs$gene_name, ignore.case = T)]$gene_name %>% unique()
C1q

write.csv(x = c(C1q, "C3") %>% sort(), 
            file = "C1 and C3 genes.csv", 
          row.names = F, quote = F)
```

```{r}
load(file = "f:/git/nichenetr/data/gr_network.rda")

# convert from human to muse symbol
gr_network$from <- gr_network$from %>% convert_human_to_mouse_symbols()
gr_network$to <- gr_network$to %>% convert_human_to_mouse_symbols()

gr_network <- gr_network %>% 
    dplyr::filter(!is.na(from), !is.na(to))

gr_network %>% 
    dplyr::filter(toupper(to) %in% toupper(c(C1q, "C3"))) %>% 
    dplyr::select(from, to) %>% 
    arrange(to) %>% 
    magrittr::set_colnames(value = c("regulator", "target")) %>% 
    write.csv(file = "C1C3-regulators.csv", 
                row.names = F, quote = F)
```