---
title: "C1aqa upstream signal"
author: "yincy"
date: "11/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(org.Mm.eg.db)
library(tidygraph)
library(ggraph)
library(igraph)
library(stringr.plus)
```


# load KEGG pathway  
```{r}
all_path_df <- read.csv(file = "../res/P2ry12/all_pathways_df.csv", 
                        stringsAsFactors = F)

all_path_df %>% dim()
all_path_df %>% pull(type) %>% table()
all_path_df %>% pull(subtype) %>% table()

all_path_df %>% head()
all_path_df <- all_path_df %>% distinct(from, to, .keep_all = T)
all_path_df %>% dim()

all_path_df %>% 
  dplyr::filter(type == "maplink")

all_path_df <- all_path_df %>% 
  dplyr::filter(type != "maplink")
all_path_df %>% dim()

all_path_df$from <- gsub("mmu:", replacement = "", all_path_df$from)
all_path_df$to <- gsub("mmu:", replacement = "", all_path_df$to)

all_path_df %>% dim()
all_path_df %>% head()
```

## add subtype information  
```{r}
# get KEGG compound information
# KEGG_compounds <- keggList("compound")
# KEGG_compounds[10:20]
# saveRDS(object = KEGG_compounds, file = "KEGG_compounds.rds")
KEGG_compounds <- readRDS(file = "KEGG_compounds.rds")
KEGG_compound_ids <- names(KEGG_compounds)

pat_location <- str_locate(string = KEGG_compounds, pattern = ";")
ll <- pat_location[, 1]

KEGG_compounds_value <- as.vector(KEGG_compounds)
KEGG_compounds_value[10:20]

extracted_str <- c()
for(i in seq_along(ll)){
  if(is.na(ll[i])){
    extracted_str <- append(extracted_str, KEGG_compounds_value[i])
  }else{
    extracted_str <- append(extracted_str, substr(KEGG_compounds_value[i], start = 1, stop = ll[i] - 1))
  }
}

KEGG_compounds_to_display <- str_trim(extracted_str, "both")
names(KEGG_compounds_to_display) <- KEGG_compound_ids
KEGG_compounds_to_display[10:20]
```

```{r}
# get KEGG gene information
# KEGG_mmu_genes <- keggList("mmu")
# saveRDS(object = mmu_genes, file = "KEGG_mmu_genes.rds")
KEGG_mmu_genes <- readRDS(file = "KEGG_mmu_genes.rds")
KEGG_mmu_genes %>% head()

library(org.Mm.eg.db)
KEGG_mmu_genes_df <- AnnotationDbi::select(x = org.Mm.eg.db, 
                       keys = KEGG_mmu_genes, 
                       keytype = "ENTREZID", 
                       columns = c("ENTREZID", "SYMBOL"))
KEGG_mmu_genes_df

KEGG_mmu_genes_to_display <- KEGG_mmu_genes_df$SYMBOL
names(KEGG_mmu_genes_to_display) <- KEGG_mmu_genes_df$ENTREZID
KEGG_mmu_genes_to_display %>% head()
```

```{r}
# get KEGG glycan information  
# KEGG_glycan <- keggList("glycan")
# saveRDS(object = KEGG_glycan, file = "KEGG_glycan.rds")
KEGG_glycan <- readRDS(file = "KEGG_glycan.rds")
KEGG_glycan %>% head()

KEGG_glycan_ids <- names(KEGG_glycan)
KEGG_glycan_ids %>% head()

KEGG_glycan_values <- KEGG_glycan %>% as.vector()
KEGG_glycan_values %>% head()

pat_location <- str_locate(KEGG_glycan, ";")
pat_location %>% dim()
ll <- pat_location[, 1]

extracted_str <- c()
for(i in seq_along(ll)){
  if(is.na(ll[i])){
    extracted_str <- append(extracted_str, KEGG_glycan_values[i])
  }else{
    extracted_str <- append(extracted_str, substr(KEGG_glycan_values[i], start = 1, stop = ll[i] - 1))
  }
}

KEGG_glycan_to_dispaly <- str_trim(extracted_str, "both")
names(KEGG_glycan_to_dispaly) <- KEGG_glycan_ids
KEGG_glycan_to_dispaly[1:10]
```

```{r}
# get KEGG drug information 
# KEGG_drug <- keggList("drug")
# saveRDS(object = KEGG_drug, file = "KEGG_drug.rds")
KEGG_drug <- readRDS(file = "KEGG_drug.rds")
KEGG_drug %>% head()

KEGG_drug_ids <- names(KEGG_drug)
KEGG_drug_values <- KEGG_drug %>% as.vector()
KEGG_drug_values %>% head()

pat_location <- str_locate(string = KEGG_drug, pattern = ";")
ll <- pat_location[, 1]

extracted_str <- c()
for(i in seq_along(ll)){
  if(is.na(ll[i])){
    extracted_str <- append(extracted_str, KEGG_drug_values[i])
  }else{
    extracted_str <- append(extracted_str, substr(KEGG_drug_values[i], start = 1, stop = ll[i] - 1))
  }
}

KEGG_drug_to_display <- extracted_str

## remove parenthesis 
KEGG_drug_to_display <- str_replace(KEGG_drug_to_display, "[ ]*\\(?[[:alnum:][:punct:]]*\\)?$", "")
names(KEGG_drug_to_display) <- KEGG_drug_ids
KEGG_drug_to_display %>% head()
```

```{r}
# some rows in from and to contain multiple ids, retain only the first one
ll <- str_locate(all_path_df$from, " ") %>% .[, 1]
all_path_df[!(ll %>% is.na()), ]

for(i in seq_along(ll)){
  if(is.na(ll[i])){
    all_path_df$from[i] <- all_path_df$from[i]
  }else{
    all_path_df$from[i] <- str_extract_before(all_path_df$from[i], " ")
  }
}


ll <- str_locate(all_path_df$to, " ") %>% .[, 1]
all_path_df[!(ll %>% is.na()), ]

for(i in seq_along(ll)){
  if(is.na(ll[i])){
    all_path_df$to[i] <- all_path_df$to[i]
  }else{
    all_path_df$to[i] <- str_extract_before(all_path_df$to[i], " ")
  }
}

all_path_df$from <- str_trim(string = all_path_df$from, side = "both")
all_path_df$to <- str_trim(string = all_path_df$to, side = "both")

names_to_display <- c(KEGG_mmu_genes_to_display, 
                      KEGG_compounds_to_display, 
                      KEGG_drug_to_display, 
                      KEGG_glycan_to_dispaly)
# saveRDS(object = names_to_display, file = "../data/KEGG/names_to_display.rds")
```


```{r}
subtype_element <- data.frame(
  name = c("compound", "hidden compound", "activation", "inhibition", 
           "expression", "repression", "indirect effect", "state change", 
           "binding/association", "dissociation", "missing interaction", 
           "phosphorylation", "dephosphorylation", "glycosylation", "ubiquitination", 
           "methylation"), 
  value = c(NA, 
            NA, 
            "-->", "--|", "-->", "--|", "..>", 
            "...", "---", "-+-", "-/-",
            "+p", "-p", "+g", "+u", "+m"), 
  stringsAsFactors = F
)

subtype_element

vl <- subtype_element$value
names(vl) <- subtype_element$name

all_path_df$subtype %>% unique()
intersect(all_path_df$subtype %>% unique(), subtype_element$name)

all_path_df$subtype_value <- vl[all_path_df$subtype]
all_path_df %>% dplyr::filter(subtype != "compound")

## add edge and node info
all_path_df$angle <- ifelse(all_path_df$subtype == "inhibition", 90, 30)
all_path_df$edge_label <- ifelse(grepl("[a-z]", all_path_df$subtype_value), all_path_df$subtype_value, NA)
all_path_df$edge_label <- ifelse(is.na(all_path_df$edge_label), "", all_path_df$edge_label)

# lty <- c(rep(1, 5), 5, 1, 3, 1, 5, 3, 5, 1, 3, 1)
lty <- c("compound" = "F1", 
         "NA" = "solid", 
         "activation" = "solid", 
         "inhibition" = "solid", 
         "expression" = "solid", 
         "binding/association" = "longdash", 
         "missing interaction" = "12345678", 
         "phosphorylation" = "solid", 
         "ubiquitination" = "solid", 
         "dephosphorylation" = "solid", 
         "indirect effect" = "dotted", 
         "dissociation"  = "dotdash", 
         "repression" = "solid", 
         "state change" = "4C88C488", 
         "glycosylation" = "solid")
names(lty) <- all_path_df$subtype %>% unique() %>%  as.character()
all_path_df$lty <- lty[all_path_df$subtype]

all_path_df$lty <- ifelse(is.na(all_path_df$lty), "solid", all_path_df$lty)

#saveRDS(object = all_path_df, file = "../data/KEGG/all_path_df_formated.rds")
```

```{r}
names_to_display[names_to_display == "C3"]
```

```{r}

df
```



```{r}
df <- all_path_df[, c("from", "to")]
df$from_symbol <- names_to_display[df$from]
df$to_symbol <- names_to_display[df$to]

ig <- graph_from_data_frame(d = df[, c("from_symbol", "to_symbol")], directed = T)
distance_to_C3_all_path <- shortest_paths(ig, from = 'C3', to = V(ig), mode = "in")[[1]]

list2df <- function(list){ 
  maxL <- sapply(list, length) %>% max()
  for(i in seq_along(list)){
    l = length(list[[i]])
    if(l < maxL){
      list[[i]] <- append(list[[i]], values = rep("", (maxL - l)))
    }
  }
  list <- as.data.frame(list)
  colnames(list) <- NULL
  list <- t(list)
  colnames(list) <- paste(rep("order", times = maxL), 0:(maxL - 1), sep = "_")
  return(as.data.frame(list))
}

all_path_nodes <- list2df(lapply(distance_to_C3_all_path, as_ids))
all_path_nodes <- all_path_nodes %>% filter(!(nchar(order_0) == 0))
write.table(x = all_path_nodes, file = "../res/C1q-C3/C3_signal_paths.csv", row.names = F, quote = F, sep = "|")


# inter_len <- apply(all_path_nodes, 1, intersect, y = c("13136", "12266")) %>% 
#   lapply(na.omit) %>% 
#   sapply(length) %>% table()
# 
# 
# filter_index <- apply(all_path_nodes, 1, is.na) %>% 
#   apply(2, sum) 

retained_path <- all_path_nodes

o1 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_1) %>% unique()),
         to %in% (retained_path %>% pull(order_0) %>% unique()))

o2 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_2) %>% unique()),
         to %in% (retained_path %>% pull(order_1) %>% unique()))

o3 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_3) %>% unique()), 
         to %in% (retained_path %>% pull(order_2) %>% unique()))

o4 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_4) %>% unique()), 
         to %in% (retained_path %>% pull(order_3) %>% unique()))

o5 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_5) %>% unique()), 
         to %in% (retained_path %>% pull(order_4) %>% unique()))

o6 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_6) %>% unique()), 
         to %in% (retained_path %>% pull(order_5) %>% unique()))

o7 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_7) %>% unique()), 
         to %in% (retained_path %>% pull(order_6) %>% unique()))

o8 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_8) %>% unique()), 
         to %in% (retained_path %>% pull(order_7) %>% unique()))

o9 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_9) %>% unique()), 
         to %in% (retained_path %>% pull(order_8) %>% unique()))

o10 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_10) %>% unique()), 
         to %in% (retained_path %>% pull(order_9) %>% unique()))

o11 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_11) %>% unique()), 
         to %in% (retained_path %>% pull(order_10) %>% unique()))

o12 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_12) %>% unique()), 
         to %in% (retained_path %>% pull(order_11) %>% unique()))

o13 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_13) %>% unique()), 
         to %in% (retained_path %>% pull(order_12) %>% unique()))

o14 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_14) %>% unique()), 
         to %in% (retained_path %>% pull(order_13) %>% unique()))

o15 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_15) %>% unique()), 
         to %in% (retained_path %>% pull(order_14) %>% unique()))

o16 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_16) %>% unique()), 
         to %in% (retained_path %>% pull(order_15) %>% unique()))

o17 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_17) %>% unique()), 
         to %in% (retained_path %>% pull(order_16) %>% unique()))

o18 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_18) %>% unique()), 
         to %in% (retained_path %>% pull(order_17) %>% unique()))

o19 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_19) %>% unique()), 
         to %in% (retained_path %>% pull(order_18) %>% unique()))

o20 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_20) %>% unique()), 
         to %in% (retained_path %>% pull(order_19) %>% unique()))

o21 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_21) %>% unique()), 
         to %in% (retained_path %>% pull(order_20) %>% unique()))

o22 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_22) %>% unique()), 
         to %in% (retained_path %>% pull(order_21) %>% unique()))

o23 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_23) %>% unique()), 
         to %in% (retained_path %>% pull(order_22) %>% unique()))

o24 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_24) %>% unique()), 
         to %in% (retained_path %>% pull(order_23) %>% unique()))

o25 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_25) %>% unique()), 
         to %in% (retained_path %>% pull(order_24) %>% unique()))

o26 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_26) %>% unique()), 
         to %in% (retained_path %>% pull(order_25) %>% unique()))

o27 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_27) %>% unique()), 
         to %in% (retained_path %>% pull(order_26) %>% unique()))

o28 <- all_path_df %>% 
  filter(from %in% (retained_path %>% pull(order_28) %>% unique()), 
         to %in% (retained_path %>% pull(order_27) %>% unique()))


filtered_path <- rbind(o1, o2, o3, o4) 
                       # o5, o6, o7, o8,
                       # o9, o10, o11, o12, o13, o14, o15,
                       # o16, o17, o18, o19, o20, o21, o22,
                       # o23, o24, o25, o26, o27, o28)

filtered_path <- filtered_path %>% dplyr::distinct(from, to, .keep_all = T)
```

```{r}
N <- tibble::tibble(
  ids = c(filtered_path$from, filtered_path$to) %>% unique()
) %>% 
  mutate(shape = ifelse(grepl("^cpd:|^gl:|^dr:", ids, ignore.case = F), "compound", "gene")) 

E <- filtered_path %>% 
  dplyr::select(from, to, everything())
```


```{r, message=FALSE, warning=FALSE}
g <- tbl_graph(nodes = N, edges = E, directed = T)

# ll <- create_layout(g, "nicely")
```

```{r, message=FALSE, warning=FALSE}
g %>% 
  mutate(dist_to_C3 = bfs_dist(root = .N()$ids == "12266", mode = "in")) %>% 
  ggraph(layout = "nicely") +
  geom_edge_link(aes(filter = (angle == "90"), edge_linetype = lty, label = edge_label), 
                 arrow = arrow(angle = 90, length = unit(0.3, "mm")), 
                 edge_width = 0.1, 
                 start_cap = circle(1, "mm"), 
                 end_cap = circle(1, "mm"), 
                 angle_calc = "along", 
                 label_size = 0.3, 
                 show.legend = T) +
  geom_edge_link(aes(filter = (angle == '30'), edge_linetype = lty, label = edge_label), 
                 arrow = arrow(angle = 30, length = unit(0.5, "mm")), 
                 edge_width = 0.1, 
                 start_cap = circle(1, "mm"), 
                 end_cap = circle(1, "mm"), 
                 angle_calc = "along", 
                 label_size = 0.3, 
                 show.legend = T) +
  geom_node_point(aes(shape = shape), 
                  color = "grey", 
                  size = 2, 
                  show.legend = F) +
  geom_node_point(aes(shape = shape, filter = (ids %in% c("12266"))), 
                  color = "red", 
                  size = 2, 
                  show.legend = F) +
  scale_shape_manual(values = c("compound" = 15, "gene" = 16)) +
  geom_node_text(aes(label = names_to_display[.N()$ids]), size = 0.7) +
  scale_edge_linetype_manual(name = "interaction type", 
                             values = c("solid" = "solid", "longdash" = "longdash", 
                                        "F1" = "F1", "dotted" = "dotted", 
                                        "dotdash" = "dotdash", "12345678" = "12345678", 
                                        "4C88C488" = "4C88C488"), 
                             labels = c("state change", "dissiciation", 
                                        "indirect effect", "compound", 
                                        "binding/association", 
                                        "activation/expression")) +
  guides(shape = F)


ggsave(filename = "../res/C1q-C3/C3.pdf")
```


```{r}
all_path_df %>% filter(from == "12269" | to == "12269")
```


```{r}
all_path_nodes
```




