---
title: "P2ry12-GO"
author: "yincy"
date: "11/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(edgeR)
library(org.Mm.eg.db)
library(magrittr)
library(ggraph)
library(tidygraph)
library(stringr.plus)
library(stringr)
```


# Go analysis  
```{r}
filtered_pvn <- read.csv(file = "../res/P2ry12/pvn_filtered.csv")

pvn_A3_DEG_up <- filtered_pvn %>% 
    filter(pvn_A3_log2FC >= 1) %>% 
    pull(geneid_symbol)

pvn_A3_DEG_down <- filtered_pvn %>% 
    filter(pvn_A3_log2FC <= -1) %>% 
    pull(geneid_symbol)

pvn_L3_DEG_up <- filtered_pvn %>% 
    filter(pvn_L3_log2FC >= 1) %>% 
    pull(geneid_symbol)

pvn_L3_DEG_down <- filtered_pvn %>% 
    filter(pvn_L3_log2FC <= -1) %>% 
    pull(geneid_symbol)

pvn_A14_DEG_up <- filtered_pvn %>% 
    filter(pvn_A14_log2FC >= 1) %>% 
    pull(geneid_symbol)

pvn_A14_DEG_down <- filtered_pvn %>% 
    filter(pvn_A14_log2FC <= -1) %>% 
    pull(geneid_symbol)

pvn_L14_DEG_up <- filtered_pvn %>% 
    filter(pvn_L14_log2FC >= 1) %>% 
    pull(geneid_symbol)

pvn_L14_DEG_down <- filtered_pvn %>% 
    filter(pvn_L14_log2FC <= -1) %>% 
    pull(geneid_symbol)
```


```{r}
pvn_A3_L3_DEG_up <- intersect(pvn_A3_DEG_up, pvn_L3_DEG_up)
pvn_A3_L3_DEG_down <- intersect(pvn_A3_DEG_down, pvn_L3_DEG_down)

pvn_A14_L14_DEG_up <- intersect(pvn_A14_DEG_up, pvn_L14_DEG_up)
pvn_A14_L14_DEG_down <- intersect(pvn_A14_DEG_down, pvn_L14_DEG_down)
```


```{r}
# Using Ang and L-name intersects DEG as background genes
bg_genes_3 <- c(pvn_A3_L3_DEG_up, pvn_A3_L3_DEG_down)
bg_genes_df_3 <- AnnotationDbi::select(org.Mm.eg.db, 
                      keys = bg_genes_3, 
                      keytype = "SYMBOL", 
                      columns = c("SYMBOL", "ENTREZID"))

bg_genes_14 <- c(pvn_A14_L14_DEG_up, pvn_A14_L14_DEG_down)
bg_genes_df_14 <- AnnotationDbi::select(org.Mm.eg.db, 
                      keys = bg_genes_14, 
                      keytype = "SYMBOL", 
                      columns = c("SYMBOL", "ENTREZID"))
```


```{r}
all_path_df <- read.csv(file = "../res/P2ry12/all_pathways_df.csv", 
                        stringsAsFactors = F)

all_path_df %>% dim()
all_path_df %>% pull(type) %>% table()
all_path_df %>% pull(subtype) %>% table()

all_path_df %>% head()
all_path_df <- all_path_df %>% distinct(from, to, .keep_all = T)
all_path_df %>% dim()

all_path_df %>% 
  dplyr::filter(type == "maplink")

all_path_df <- all_path_df %>% 
  dplyr::filter(type != "maplink")
all_path_df %>% dim()

all_path_df$from <- gsub("mmu:", replacement = "", all_path_df$from)
all_path_df$to <- gsub("mmu:", replacement = "", all_path_df$to)


ll <- str_locate(all_path_df$from, " ") %>% .[, 1]
all_path_df[!(ll %>% is.na()), ]

for(i in seq_along(ll)){
  if(is.na(ll[i])){
    all_path_df$from[i] <- all_path_df$from[i]
  }else{
    all_path_df$from[i] <- str_extract_before(all_path_df$from[i], " ")
  }
}


ll <- str_locate(all_path_df$to, " ") %>% .[, 1]
all_path_df[!(ll %>% is.na()), ]

for(i in seq_along(ll)){
  if(is.na(ll[i])){
    all_path_df$to[i] <- all_path_df$to[i]
  }else{
    all_path_df$to[i] <- str_extract_before(all_path_df$to[i], " ")
  }
}

all_path_df$from <- str_trim(string = all_path_df$from, side = "both")
all_path_df$to <- str_trim(string = all_path_df$to, side = "both")


N <- tibble::tibble(
  ids = c(all_path_df$from, all_path_df$to) %>% unique()
) %>% 
  mutate(shape = ifelse(grepl("^cpd:|^gl:|^dr:", ids, ignore.case = F), "21", "22")) 

E <- all_path_df %>% 
  dplyr::select(from, to, everything())

g <- tbl_graph(nodes = N, edges = E, directed = T)

P2ry12_downstream_genes <- g %>% 
  mutate(dist_to_p2ry12 = bfs_dist(root = .N()$ids == "70839", mode = "out")) %>% 
  as_tibble() %>% 
  filter(!is.na(dist_to_p2ry12)) %>% 
  pull(ids)

P2ry12_downstream_genes <- P2ry12_downstream_genes[grepl("^[0-9]", P2ry12_downstream_genes)]
P2ry12_downstream_genes_df <- AnnotationDbi::select(org.Mm.eg.db, 
                                                    keys = P2ry12_downstream_genes, 
                                                    keytype = "ENTREZID", 
                                                    columns = c("SYMBOL", "ENTREZID"))
```



```{r}

pvn_A3_L3_DEG_up_df <- AnnotationDbi::select(x = org.Mm.eg.db, 
                              keys = intersect(pvn_A3_L3_DEG_up, P2ry12_downstream_genes_df$SYMBOL), 
                              keytype = "SYMBOL", 
                              columns = c("SYMBOL", "ENTREZID"))

pvn_A3_L3_DEG_down_df <- AnnotationDbi::select(x = org.Mm.eg.db, 
                                keys = intersect(pvn_A3_L3_DEG_down, P2ry12_downstream_genes_df$SYMBOL), 
                                keytype = "SYMBOL", 
                                columns = c("ENTREZID", "SYMBOL"))


pvn_A14_L14_DEG_up_df <- AnnotationDbi::select(x = org.Mm.eg.db, 
                                keys = intersect(pvn_A14_L14_DEG_up, P2ry12_downstream_genes_df$SYMBOL), 
                                keytype = "SYMBOL", 
                                columns = c("SYMBOL", "ENTREZID"))

pvn_A14_L14_DEG_down_df <- AnnotationDbi::select(x = org.Mm.eg.db, 
                                  keys = intersect(pvn_A14_L14_DEG_down, P2ry12_downstream_genes_df$SYMBOL), 
                                  keytype = "SYMBOL", 
                                  columns = c("SYMBOL", "ENTREZID"))
```


```{r}
# 3 days
pvn_A3_L3_DEG_up_GO <- goana(de = pvn_A3_L3_DEG_up_df$ENTREZID, 
                             species = "Mm", 
                             universe = bg_genes_df_3$ENTREZID) %>% 
  tibble::rownames_to_column("GOID") %>% 
  mutate(group = "up") %>% 
  arrange(P.DE)


pvn_A3_L3_DEG_down_GO <- goana(de = pvn_A3_L3_DEG_down_df$ENTREZID, 
                               species = "Mm", 
                               universe = bg_genes_df_3$ENTREZID) %>% 
  tibble::rownames_to_column("GOID") %>% 
  mutate(group = "down") %>% 
  arrange(P.DE)

pvn_A3_L3_DEG_GO <- rbind(pvn_A3_L3_DEG_up_GO %>% 
                            arrange(P.DE) %>% 
                            head(15), 
                          pvn_A3_L3_DEG_down_GO %>% 
                            arrange(P.DE) %>% 
                            head(15))


# 14 days
pvn_A14_L14_DEG_up_GO <- goana(de = pvn_A14_L14_DEG_up_df$ENTREZID, 
                               species = "Mm", 
                               universe = bg_genes_df_14$ENTREZID) %>% 
  tibble::rownames_to_column("GOID") %>% 
  mutate(group = "up") %>% 
  arrange(P.DE)

pvn_A14_L14_DEG_down_GO <- goana(de = pvn_A14_L14_DEG_down_df$ENTREZID, 
                                 species = "Mm", 
                                 universe = bg_genes_df_14$ENTREZID) %>% 
  tibble::rownames_to_column("GOID") %>% 
  mutate(group = "down") %>% 
  arrange(P.DE)

pvn_A14_L14_DEG_GO <- rbind(pvn_A14_L14_DEG_up_GO %>% 
                              arrange(P.DE) %>% 
                              head(15), 
                            pvn_A14_L14_DEG_down_GO %>% 
                              arrange(P.DE) %>% 
                              head(15))
```


```{r}
write.csv(x = pvn_A3_L3_DEG_GO, file = "pvn_A3_L3_DEG_GO.csv", row.names = F, quote = F)
pvn_A3_L3_DEG_GO <- read.csv(file = "pvn_A3_L3_DEG_GO.csv")

pvn_A3_L3_DEG_GO %>% 
  mutate(log10Pvalue = log10(P.DE),
         multi_factor = ifelse(group == "up", -1, 1), 
         p_value = log10Pvalue * multi_factor) %>%  
  ggplot(aes(p_value, reorder(Term, P.DE), fill = group)) +
  geom_bar(stat = "identity", show.legend = F) +
  scale_y_discrete(name = NULL) +
  scale_x_continuous(name = "log10(p.value)", 
                     breaks = c(-10.0, -5.0, 0.0, 5.0, 10.0, 15), 
                     labels = c("10.0", "5.0", "0.0", "5.0", "10.0", "15"), 
                     expand = c(0, 0)) +
  scale_fill_manual(name = NULL, values = c("up" = "red", "down" = "blue")) +
  facet_grid(group ~ ., scales = "free_y") +
  theme(strip.background = element_rect(fill = "grey70"), 
        strip.text.y = element_text(color = "black"), 
        panel.background = element_rect(fill = "grey95"))

ggsave(filename = "../res/P2ry12/A3_L3_GO.tiff")
```



```{r}
write.csv(x = pvn_A14_L14_DEG_GO, file = "pvn_A14_L14_DEG_GO.csv", row.names = F, quote = F)
pvn_A14_L14_DEG_GO <- read.csv(file = "pvn_A14_L14_DEG_GO.csv")

pvn_A14_L14_DEG_GO %>% 
  mutate(log10Pvalue = log10(P.DE),
         multi_factor = ifelse(group == "up", -1, 1), 
         p_value = log10Pvalue * multi_factor) %>% 
  ggplot(aes(p_value, reorder(Term, P.DE), fill = group)) +
  geom_bar(stat = "identity", show.legend = F) +
  scale_y_discrete(name = NULL) +
  scale_x_continuous(name = "log10(p.value)", 
                     breaks = c(-15, -10, -5, 0, 5, 10, 15, 20), 
                     labels = c("15.0", "10.0", "5.0", "0.0", "5.0", "10.0", "15.0", "20.0"), 
                     expand = c(0, 0)) +
  scale_fill_manual(name = NULL, values = c("up" = "red", "down" = "blue"))+
  facet_grid(group ~ ., scales = "free_y") +
  theme(strip.background = element_rect(fill = "grey70"), 
        strip.text.y = element_text(color = "black"), 
        panel.background = element_rect(fill = "grey95"))


ggsave(filename = "../res/P2ry12/A14_L14_GO.tiff")
```




