---
title: "Introduction"
author: "yincy"
date: "6/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
The caret package (short for Classification And REgression Training) is a set of functions that attempt to streamline the process for creating predictive models. The package contains tools for:  

- data splitting  
- pre-processing  
- feature selection  
- model tuning using resampleing  
- variable importance estimation  

as well as other functionality.  

There are many different modeling functions in R. Some have different syntax for model training and/or prediction. The package started off as a way to provide a uniform interface the functions themselves, as well as a way to standardize common tasks (such parameter tuning and variable importance).  


Some resources:  

- The book Applied Predictive Modeling features **caret** and over 40 other R packages. It is on sale at Amazon or the the publisher’s website. There is a [companion website](http://appliedpredictivemodeling.com/) too.  

- There is also a paper on caret in the Journal of Statistical Software. The example data can be obtained [here](https://topepo.github.io/caret/descr.RData)(the predictors) and [here](https://topepo.github.io/caret/mutagen.RData) (the outcomes).  

- There is a [webinar](http://www.youtube.com/watch?v=7Jbb2ItbTC4) for the package on Youtube that was organized and recorded by Ray DiGiacomo Jr for the Orange County R User Group.  

- At [useR! 2014](http://user2014.stat.ucla.edu/), I was [interviewed](http://youtu.be/YmHyAHkjX_A) and discussed the package and the book.

- DataCamp has a [beginner’s tutorial on machine learning in R](https://www.datacamp.com/courses/machine-learning-toolbox) using `caret`.  
